### ISSUE TITLE
Scope of SharpWindows

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#1]
Hi, I know you have limited the scope to just the Core Direct X 11 and 12 capabilities.  Just wondeirng if once you have completed your initial goals you would consider Direct Input XAudio later?  May want to contribute at some point seeing that Sharpdx is done.  At that you are using Numerics instead of rolling your own.  

Happy to discuss.

**Comment by amerkoleci** [comment]
Hi,
As I described on SharpDX issue, I plan to have modern API first, using of System.Runtime.CompilerServices.Unsafe and System.Numerics.Vectors and shared mathematics library which I'm using in my game engine as well (https://github.com/amerkoleci/Vortice.Mathematics), once I have good D3D11 and D3D12 (which I'm almost so far), I can add XAudio, DirectInput etc

**Comment by h1cks** [comment]
Well happy to look into it and assist if you're happy for contributions on that front.  Talk sometime.

**Comment by nathan-alden** [comment]
It's so sad that Microsoft doesn't see the potential of investing in a Microsoft-maintained DirectX shim. Then again, they seem not to care about the future of Windows itself much anymore, so I guess I shouldn't be surprised.

Regardless, and despite my busy schedule and my family's needs, I'm interested enough in a replacement for SharpDX that I might be willing to participate. Unfortunately, COM interop in C# is not my specialty, and I'm sure there are many intricacies that must be considered before I could jump in. Do you know of any reference materials that talk in depth about how to efficiently wrap COM objects in C#? Looking at SharpDX's and your source code isn't really giving me the underlying knowledge I'd need to avoid making mistakes.

Also, I'm curious if it would be simpler or in any way more useful to develop a shim in Managed C++ (C++/CLI). Do you know if this has been considered at any point?

I'm not sure how much time you have, but if you are serious about on-boarding contributors you should put together a guide, given that the area of COM interop is entirely useless to almost every C# developer.

**Comment by nathan-alden** [comment]
I did a bit of research and it seems you're using something called [SharpGenTools](https://sharpgentools.readthedocs.io/en/latest/) to presumably efficiently generate wrappers. The issue is, how do I know what to put in the Mappings file? The declarative nature of XML doesn't lend itself to understanding.

If I may suggest: Your contribution guide should introduce experienced C#/.NET developers who may want to contribute to the special nature of COM interop and also the SharpGenTools libraries.

**Comment by amerkoleci** [comment]
Hi,
Yeap, SharpGenTools is used and its not that difficult to learn, I agree that C++/CLI would be more handcrafted but even more difficult to maintain and it doesn't work under .NET Core.

You can still digg in Mapping.xml changes and see how bindings works, then SharpGenTools has good documentation for getting started stuff.

**Comment by h1cks** [comment]
Just to add.  The .NET standard 2.0 support will be welcome.  I just spent the day playing around with the porting of apps to .NET 3.0 -> [porting to .NET 3.0](https://www.youtube.com/watch?v=upVQEUc_KwU&list=LLQgOLROabm_1W6NIsa0koBw&index=2&t=0s) . My game obviously can't move to this because im using the older Sharpdx libraries.  As such, your project becomes even more relevant as SharpWindows basis is the more modern standard.  I've looked at contributing, I will probably look at adding Directinput if I get time, if I do, I will let you know so you can do a once over with the pull request.

**Comment by nathan-alden** [comment]
.NET Core 3.0 is going to be awesome. I think it's a much bigger deal than many folks are aware. It'll be nice to be able to write a .NET Core 3.0 Windows Forms app that uses all .NET Standard class libraries including SharpWindows.

**Comment by DemoBytom** [comment]
Hello,
I came across this repository from SharpDX, after it was archived.
I was wondering do you plan on releasing it on official NuGet feed, and what is the current state of Vortice.Windows?

**Comment by amerkoleci** [comment]
I'm using it in my vortice framework, it's next more net standard sharpdx successor, built around net standard libraries and not having own math stuff like SharpDX, it wraps DXGI, D3D11, D3D12, Direct Write and D2D1 so far.

I started adding Audio and XAudio part, won't add any legacy d3d9 or d3d10 parts. 

Will publish to nuget soon. 

Feel free to ask any further questions if you want.

**Comment by nathan-alden** [comment]
The 2D engine I've been writing uses Direct2D, Direct3D 11, XAudio 2 and XInput, so it'll be _really nice_ when you've completed your mappings. Can't wait to test them out!

**Comment by nathan-alden** [comment]
@amerkoleci Any chance you could do a small write-up on how you improved the architecture from SharpDX, specifically around the use of new .NET Standard primitives? I'd be very curious to hear more. Do you have a Discord or Slack channel I could join?

**Comment by amerkoleci** [comment]
Hi,
At the moment I'm just implementing stuff that SharpDX had, I would love to finish the XAudio bindings and then will add probably XInput bindings. 

As I said above it uses net standard numerics, system.drawing stuff like Point, PointF, Rectangle etc and Interop.Unsafe instead of having IL patching like SharpDX.

**Comment by nathan-alden** [comment]
@amerkoleci I remember asking you quite some time ago whether you had a guide I could use to help create bindings. I'm willing to spend some time on this but generating COM bindings is not my specialty. Would be nice to chat somehow to learn the ropes. :)

**Comment by nathan-alden** [comment]
FWIW, I did successfully get SharpGenTools to generate files given a C++ header (I used `d3dcommon.h`) but it looks like your codebase consists of far, far more than just generated code. This will probably prevent me from contributing in any meaningful way.

**Comment by amerkoleci** [comment]
I think you should take look at shargen sdk documentation, usually I use ilspy to see the compiled assembly and see if generated bindings are good

**Comment by nathan-alden** [comment]
FWIW, check out this tweet thread from xoofx: https://mobile.twitter.com/xoofx/status/1031645672821469187

I followed the SharpGenTools docs and was able to create some generated code. I suspect that's the _easy_ part, though; from my inexperienced eyes it appears that you're also writing a lot of custom code. That's the part where I'm getting stuck.

Anyway, I really only need XInput support (as others have asked for) so I suspect I won't have long to wait. Then I can at least give feedback as I move my engine from SharpDX to Vortice.

**Comment by amerkoleci** [comment]
I see,
Soon I plan to add XInput bindings, will keep you updated

**Comment by nathan-alden** [comment]
Cool, thanks. 👍 Will these libraries eventually be uploaded to nuget.org or will they be on myget, do you think? Just curious.

Do you have a donation link? I can throw a few bucks your way for taking on this project.

**Comment by nathan-alden** [comment]
Also, take a look here to read about new C# compiler intrinsics (although I suspect this will impact SharpGenTools more): https://github.com/dotnet/csharplang/blob/master/proposals/intrinsics.md

**Comment by amerkoleci** [comment]
Hi @nathan-alden ,
Probably that need to involve SharpGen, about donation part, write me privatelly maybe or on my email address.
