### ISSUE TITLE
Incorrect rectangle type used for many APIs

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#10]
I ran into an issue during my SharpDX to Vortice.Windows migration: the use of `RectangleF` by mappings. I know this is an issue with at least a few APIs but it's likely the issue is much greater in scope; I just haven't had a chance to use more APIs yet.

For an example, take a look at [`ID2D1RenderTarget::DrawBitmap` documentation](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-drawbitmap). Note how the rectangle type used is `D2D1_RECT_F`, which is indirectly defined as this:
``` C
typedef struct D2D_RECT_F {
  FLOAT left;
  FLOAT top;
  FLOAT right;
  FLOAT bottom;
} D2D_RECT_F;
```
Unfortunately, the mapping is using `System.Drawing.RectangleF`, which is defined like this:
``` C#
public struct RectangleF
{
    private float x;
    private float y;
    private float width;
    private float height;
}
```
When I pass a `RectangleF` instance, DirectX is interpreting the `width` and `height` fields as `right` and `bottom` respectively; as a result, my drawing operations are rendered incorrectly. I believe this is why SharpDX used custom types like [`RawRectangleF`](https://github.com/sharpdx/SharpDX/blob/1f89381bc08f2d8cf8d294c6c5fce8dc85a849a1/Source/SharpDX/Mathematics/Interop/RawRectangleF.cs).

It might be worth looking through all of [SharpDX's custom interop types](https://github.com/sharpdx/SharpDX/tree/1f89381bc08f2d8cf8d294c6c5fce8dc85a849a1/Source/SharpDX/Mathematics/Interop) to see what other types may have to be created. It's likely you'll have to create some custom structs and such with the correct `StructLayoutAttribute` settings.

**Comment by amerkoleci** [comment]
Hi,
Yeah, I thought they where mapping to standard Rectangle and Rectangle, will fix it soon, D2D_RECT_U need fix as well.
