### ISSUE TITLE
X3DAudio LoopInfinite missing from Vortice.XAudio2 1.8.41

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#104]
**Describe the bug**
LoopInfinite constant is not generated into the IXAudio2.cs file (from my investigations) - Vortice.XAudio2 1.8.41

I haven't pulled project and compiled myself.

**To Reproduce**

code sample:
_targetBuffer.LoopCount = IXAudio2.LoopInfinite;

Please close if its just that the constant is generating in the code base, but the latest version doesnt reflect the addition.

**Comment by amerkoleci** [comment]
Somehow it ended being generated as part of AudioBuffer, now its fixed.

**Comment by amerkoleci** [comment]
Version 1.8.46 contains the fix as well the D3D12 Video support added.

**Comment by h1cks** [comment]
Cheers, I will be looking into generating the DirectInput and Media Factory bindings over the next couple of days.  I set up Directinput in my fork, spent a few hours on it.  if I figure out the issue with Joystick State, I will clean up the code and submit a PR.  But I feel that im modelling alot of it on the old Sharpdx approach, so may need your thoughts.  Appreciate your work on everything, no hurry at the moment.

**Comment by h1cks** [comment]
<const from-macro="XAUDIO2_LOOP_INFINITE" type="int" cpp-type="int" name="LoopInfinite" class="Vortice.IXAudio2.IXAudio2" visibility="public const" />
    
needs to be,

    <const from-macro="XAUDIO2_LOOP_INFINITE" type="int" cpp-type="int" name="LoopInfinite" class="Vortice.XAudio2.IXAudio2" visibility="public const" />

Typo.  IXAudio2 = XAudio2

**Comment by h1cks** [comment]
@amerkoleci - cant reopen ticket, but issue is just a typo.

**Comment by amerkoleci** [comment]
Done, thanks!
