### ISSUE TITLE
Are you aware of Tanner Gooding's TerraFX.Interop.Windows?

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#11]
Heya, Amer. I found an official DirectX Discord where I asked about whether there was a possibility for officially-maintained bindings from Microsoft. After some interesting conversation, I was pointed to a project maintained by Tanner Gooding from Microsoft called [TerraFX.Interop.Windows](https://github.com/terrafx/terrafx.interop.windows). It appears that he's somehow using the Clang compiler to generate mappings in C#. The mappings his tool generates are _much_ more raw than what SharpGen is putting out. For example, here's the mapping for `ID2D1RenderTarget::CreateSolidColorBrush`:
```
[return: NativeTypeName("HRESULT")]
public int CreateSolidColorBrush(
    [In, NativeTypeName("D2D1_COLOR_F")] DXGI_RGBA* color,
    [In, Optional] D2D1_BRUSH_PROPERTIES* brushProperties,
    [Out] ID2D1SolidColorBrush** solidColorBrush
)
{
    fixed (ID2D1RenderTarget* This = &this)
    {
        return MarshalFunction<_CreateSolidColorBrush>(lpVtbl->CreateSolidColorBrush)(
            This,
            color,
            brushProperties,
            solidColorBrush
        );
    }
}
```
To use this, I have to enable unsafe code in my project and write lots of helper code to deal with things like checking `HRESULT`s. Certainly annoying, but if these mappings are robust and automatically generated without manual mapping configuration, it might be worth using the library.

Here's an example of a class that creates, exposes, and releases stock brushes for use throughout the application:
```
public unsafe class Brushes : IBrushes
{
    private ID2D1SolidColorBrush* _opaqueWhite;

    public ID2D1SolidColorBrush* OpaqueWhite => _opaqueWhite;

    public void Dispose()
    {
        ReleaseDeviceResources();
    }

    public void ReleaseDeviceResources()
    {
        _opaqueWhite->Release();
        _opaqueWhite= null;
    }

    public void InitializeDeviceResources(ID2D1RenderTarget* renderTarget)
    {
        ReleaseDeviceResources();

        fixed (ID2D1SolidColorBrush** opaqueWhite = &_opaqueWhite)
        {
            var opaqueWhiteColor = new DXGI_RGBA { r = 1, g = 1, b = 1, a = 1 };

            renderTarget->CreateSolidColorBrush(&opaqueWhiteColor, null, opaqueWhite);
        }
    }
}
```
As you can see, this is a lot closer to C++'s way than C#'s traditional way. I could get comfortable with that, but having `fixed` blocks all over the place, dealing with pointer dereferencing, COM-style `->Release()` instead of `IDisposable`, and no polymorphism because these types are all structs and don't implement interfaces is going to be a big pain.

**Comment by nathan-alden** [comment]
FWIW, it seems he hasn't created mappings for XAudio2 or XInput.

**Comment by amerkoleci** [comment]
Hi @nathan-alden ,
That one looks good althought it doesnt support CallI interop call when calling COM part, so far I prefer the SharpGen generation part, if there are any alternatives I will look further.

Closing now as not really an issue
