### ISSUE TITLE
DataStream Write is overwriting memory

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#110]
**Describe the bug**
Executing a write to the stream from a byte buffer overwrites memory space by gigabytes.

Code sample

```
var buffer_ = new DataStream(pixelData_.Length, true, true);

var pixelData_ = BitmapHelper.GetPixelData(bsource);

SwapARGBtoABGR(ref pixelData_);
buffer_.Write(pixelData_, 0, pixelData_.Length);
```

where as

```
var buffer_ = new DataStream(pixelData_.Length, true, true);

var pixelData_ = BitmapHelper.GetPixelData(bsource);

SwapARGBtoABGR(ref pixelData_);

for (int i =0; i < pixelData_.Length; i++)
{
    buffer_.Write(pixelData_[i]);
}
````

works fine.

**Comment by amerkoleci** [comment]
Can you try DataStream.Create method and pass pixel data there? Otherwise try the WriteRange just to see which method causes trouble?

**Comment by h1cks** [comment]
Tested create, I get a "Attempted to read or write to protected memory", similar to the Write issue before

**Comment by h1cks** [comment]
tested WriteRange, didnt throw an exception, but overwrote large amounts of memory.

some issues.

**Comment by h1cks** [comment]
Will test tomorrow more, will check this thread.  long day.

@amerkoleci
