### ISSUE TITLE
 d3dDevice.CreateTexture2D(texture2d, subresouredata[]) function possible issue.

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#111]
**Describe the bug**
Creating a subresourcedata buffer and passing a datapointer causes an exception (DX invalid parameter) 

````
 SubresourceData rect_ = new SubresourceData(buffer_.PositionPointer);

SubresourceData[] buffers_ = new SubresourceData[1];

buffers_[0] = rect_;

  t2d_ = d3dDevice.CreateTexture2D(textureDesc, buffers_  );
````

where as 

````
t2d_ = d3dDevice.CreateTexture2D(textureDesc);

MappedSubresource resource_ = new MappedSubresource(buffer_.PositionPointer, stride_, 0);

d3dDevice.ImmediateContext.UpdateSubresource(resource_, t2d_);
````

is functional.

**Comment by amerkoleci** [comment]
Enable native debugging and can you report the error d3d11 debug layer reports?

**Comment by h1cks** [comment]
SubresourceData rect_ = new SubresourceData(buffer_.PositionPointer. stride_);

fixed it.  Debug layer showed an error on the exception I caught.  Think this was just down to missing something silly.
