### ISSUE TITLE
DXC container reflection loading exception.

### ISSUE THREAD

**Issue by shenzhou05** [amerkoleci/Vortice.Windows#117]
Hi, amerkoleci. Would you like to add support for mesh shaders and variable rate shading in DirectX 12 Ultimate?
https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12MeshShaders
https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12VariableRateShading

**Comment by amerkoleci** [comment]
Its already supported, what did you find wrong?

**Comment by shenzhou05** [comment]
I can't compile MS shader with DXC.

**Comment by amerkoleci** [comment]
Any chance I can get more info? What errors you got? This way I'm gonna close the issue

**Comment by shenzhou05** [comment]
This is how i get shader reflection：

public static ID3D12ShaderReflection GetShaderReflection(string source)
{
    var library = Dxc.CreateDxcLibrary();
    var sourceBlob = Dxc.CreateBlobForText(library, source);
    var loader = Dxc.CreateDxcContainerReflection();
    loader.Load(sourceBlob);
    loader.FindFirstPartKind(Dxc.DFCC_DXIL, out var partIndex);
    loader.GetPartReflection(partIndex, typeof(ID3D12ShaderReflection).GUID, out var nativePtr);
    return new ID3D12ShaderReflection(nativePtr);
}

When DXC loads sourceBlob, an exception occurred :
 System.ArgumentException "Value does not fall within the expected range."
at Vortice.Dxc.IDxcContainerReflection.Load(IDxcBlob container)

**Comment by amerkoleci** [comment]
Modern DXC API just landed, here you can see how I compile shader with modern dxc compiler and getting the D3D12 reflection https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/Vortice.SampleFramework/D3D12GraphicsDevice.cs#L190

**Comment by shenzhou05** [comment]
> Modern DXC API just landed, here you can see how I compile shader with modern dxc compiler and getting the D3D12 reflection https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/Vortice.SampleFramework/D3D12GraphicsDevice.cs#L190

Thanks.
