### ISSUE TITLE
Invalid IL in Interop.Read

### ISSUE THREAD

**Issue by SomeAnonDev** [amerkoleci/Vortice.Windows#119]
The JIT crashes when trying to compile the [Interop.Read](https://github.com/amerkoleci/Vortice.Windows/blob/a95812c1ee6ef9f5edbdf400d27f5c320e999599/src/Vortice.DirectX/Interop.cs#L21) method
![image](https://user-images.githubusercontent.com/6377116/105865472-05e59600-6004-11eb-8de1-2f441463f4c3.png)

Here's a repro project: [vortice-invalid-il](https://github.com/SomeAnonDev/vortice-invalid-il).

**Comment by amerkoleci** [comment]
Where it happens? Code snippet? Stack trace?

**Comment by SomeAnonDev** [comment]
Not sure what exactly you're asking for since I've already provided a repro project.
I did some more experimentation though, and I'm pretty sure it's a SharpGen issue.
Here's [another repro project](https://github.com/SomeAnonDev/sharpgen-invalid-il) that doesn't even reference Vortice, but contains a Read method identical to the one in Vortice.
I don't believe there's anything wrong with your ``Read`` implementation — normally it works just fine, but if you add a reference to SharpGen, it will crash with invalid IL.
I've yet to file an issue on their repo — first I'd like to check if it's already been fixed in the dev branch.

**Comment by SomeAnonDev** [comment]
For now there is a workaround — we could rewrite the ``Interop`` methods to use SharpGen's ``MemoryHelpers`` class. They're implemented more or less the same way, but their IL remains unaffected by SharpGen's own assembly patcher, which means there'll be no crashes.

**Comment by amerkoleci** [comment]
Thanks for info, if you don't mind send PR, thank you :)

**Comment by SomeAnonDev** [comment]
Looks like I was wrong after all, and it's not gonna be as easy as rewriting the ``Interop`` methods to use ``MemoryHelpers``. I've confirmed that SharpGen 2.0 won't have this issue, but it might take a while before it releases. Perhaps it's worth submitting a fix to the 1.x branch.

**Comment by mikestek** [comment]
A quick workaround could be to rename the Interop class so that SharpGen won't touch it.
Can follow their example and call it MemoryHelpers.
I tested locally and it's working.

I can make changes throughout the solution and create a PR if this solution is liked.

**Comment by SomeAnonDev** [comment]
>A quick workaround could be to rename the Interop class so that SharpGen won't touch it.
True, but that would be a breaking changing since the Interop class is public, for whatever reason. That's why I didn't even mention this option.

**Comment by mikestek** [comment]
Here's an idea:
Leave an Interop class for the functions that work (forward call to MemoryHelpers, will still be rewritten and inlined by SharpGen) and mark with Obsolete attribute.

Mark broken functions as Obsolete too and note that they are broken plus make them throw NotImplementedException with the same note that the functions are broken. This works since if they are broken with invalid IL they would fail anyways. But in this case anyone using them would see a clear message.

**Comment by SomeAnonDev** [comment]
>Mark broken functions as Obsolete too and note that they are broken plus make them throw NotImplementedException with the same note that the functions are broken

SharpGen would still rewrite them though — it doesn't care what the original code does and whether the method is marked as Obsolete.

**Comment by amerkoleci** [comment]
I will fix it soon, we'll move to MemoryHelpers and  rename to InteropUtilities

**Comment by amerkoleci** [comment]
The latest 1.9.4-beta packages should work, please test it so I can release stable 1.9.5.

Thanks

**Comment by SomeAnonDev** [comment]
@amerkoleci Thanks. I'm no longer seeing any crashes.
