### ISSUE TITLE
Wrong majorness in DxcCompiler.Compile

### ISSUE THREAD

**Issue by Aminator** [amerkoleci/Vortice.Windows#12]
`-Zpc` is used instead of `-Zpr` when `PackMatricesInRowMajor` is true.
https://github.com/amerkoleci/Vortice.Windows/blob/cdd75d017ab5983300c0b5da2769db2a3bc0c830/src/Vortice.Dxc/DxcCompiler.cs#L31-L38

**Comment by amerkoleci** [comment]
Fixed now
