### ISSUE TITLE
XAudio2 reverb presets cause playback silence

### ISSUE THREAD

**Issue by mrcoffeeee** [amerkoleci/Vortice.Windows#125]
Hello,

I have set a simple xaudio2 setup with a sourcevoice and want to apply the reverb effect with the reverb presets on it. With the default reverb parameters (like "Default" or  "Plate") there is some kind of reverb audible but some of the presets (like "Arena") result in silence when doing the playback. Also the audible presets sound very similar or the seem to sound the same (its hard to say if thats the cause of the presets itself or if the reverbvalues are never changed). Also if i change values of the reverbparameters manually like roomsize to the max value there is no audible difference.

**To Reproduce**
see the code and zip file attached

**Expected behavior**
With the changing of reverb presets there sould be an audible difference in the reverb sound and all presets should lead to an audible result.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 Build: 19042.844

**Code:**

            var xaudio2 = new IXAudio2(ProcessorSpecifier.DefaultProcessor);
            var mv = xaudio2.CreateMasteringVoice(1, 48000);

            var reader = new NAudio.Wave.WaveFileReader("TEST.wav");
            var array = new byte[reader.Length];
            reader.Read(array, 0, array.Length);
            var targetBuffer = new AudioBuffer(array, BufferFlags.None);
            int encoding = (int)reader.WaveFormat.Encoding;

            var waveFormat = WaveFormat.CreateCustomFormat((WaveFormatEncoding)encoding,
                reader.WaveFormat.SampleRate,
                reader.WaveFormat.Channels,
                reader.WaveFormat.AverageBytesPerSecond,
                reader.WaveFormat.BlockAlign,
                reader.WaveFormat.BitsPerSample);

            targetBuffer.LoopCount = IXAudio2.LoopInfinite;
            var reverb = Vortice.XAudio2.Fx.Fx.CreateAudioReverb();
            var revpar = new Vortice.XAudio2.Fx.ReverbParameters
            {
                WetDryMix = 100,
                RoomFilterFreq = 5000,
                ReverbGain = 20,
                ReverbDelay = 85,
                RoomSize = 50,
                DecayTime = 5000,
                LowEQCutoff = 9
            };

            // Test with reverb presets:
            // var revpresetspar = Vortice.XAudio2.Fx.Presets.Default; --> does work
            // var revpresetspar = Vortice.XAudio2.Fx.Presets.Arena; --> doesnt work

            mv.SetVolume(.9f);
            var sourceVoice = xaudio2.CreateSourceVoice(waveFormat);
            var ef = new EffectDescriptor(reverb,1);
            sourceVoice.SetEffectChain(ef);
           // sourceVoice.SetEffectParameters(0, Vortice.XAudio2.Fx.Fx.ReverbConvertI3DL2ToNative(revpresetspar, true));
            sourceVoice.SetEffectParameters(0, revpar);
            sourceVoice.EnableEffect(0);
            sourceVoice.SubmitSourceBuffer(targetBuffer);
            sourceVoice.Start();
            Console.WriteLine("Vortice XAudio2 Playing ...");
            Console.ReadKey();

[XAudio2-ReverbDemo.zip](https://github.com/amerkoleci/Vortice.Windows/files/6137128/XAudio2-ReverbDemo.zip)

**Comment by manuelxmarquez** [comment]
I couldn't compile your code, I had to change the constructor to this:
`var xaudio2 = XAudio2.XAudio2Create(ProcessorSpecifier.UseDefaultProcessor);`

I tested the underwater effect since it would probably be obvious but I couldn't tell a difference.
`var revpresetspar = Vortice.XAudio2.Fx.Presets.UnderWater;`

I haven't looked into it more than that. Might want to reference a Microsoft tutorial and see how it's done in native.

**Comment by mrcoffeeee** [comment]
i prepared a xaudio2 c++ demo and updated the uploaded vortice xaudio2demo with reverbparameters. All are set to the standard values. In the c++ version changed effectparameters are audible. In the the vortice demo nothing happens at all


[C++ XAudio2Test2.zip](https://github.com/amerkoleci/Vortice.Windows/files/6175741/C%2B%2B.XAudio2Test2.zip)
[C# Xaudio2VorticeTest.zip](https://github.com/amerkoleci/Vortice.Windows/files/6175744/C.Xaudio2VorticeTest.zip)

**Comment by amerkoleci** [comment]
I tried to improve the effect logic to avoid the copy and some marshal logic, can you try now?

**Comment by mrcoffeeee** [comment]
okay i tried that but it doesn´t change anything. Whats really strange is when i set the effectindex to "1" like this
`sourceVoice.SetEffectParameters(1, revpar);`
i get a reverbeffect but changing parameters does not have any effect. Setting the index to 0:
`sourceVoice.SetEffectParameters(0, revpar);`
just gives me the dry sound.

Doing this with a reverb presets also results in the standard reverb for every reverb preset.
`var revpresetspar = Vortice.XAudio2.Fx.Presets.Default;`
`sourceVoice.SetEffectParameters(1, Vortice.XAudio2.Fx.Fx.ReverbConvertI3DL2ToNative(revpresetspar, false));`
while setting a 0 results in some strange reverb for the "Default" preset and silence for the "Arena" preset again.

It seems like the parameters are not changeable and shouldn´t the index work with 0?

**Comment by mrcoffeeee** [comment]
Hi sorry I could not work on my project for some time but tested the code after you closed the bug. Reverb is still not working. The problem remains. I attached an updated C# demo with the latest vortice xaudio2 (1.9.143). There is an area in the program.cs-code where you can switch between 2 presets. "Default" is working at least somehow but "Arena" still results in silence.
It seems to me that reverb doesn´t work on presets with larger reverb times.
[210919 - Vortice NetCORE DEMO.zip](https://github.com/amerkoleci/Vortice.Windows/files/7192862/210919.-.Vortice.NetCORE.DEMO.zip)

**Comment by manuelxmarquez** [comment]
I checked this a few times but I finally found out the issue. It was not easy to find and I spent quite a bit of time on it but the struct has the wrong packing. I submitted a pull request to fix it.

I also took your sample project and incorporated it into the Vortice solution for easier debugging. I uploaded the commit in case more bugs are found and it might be a good place to start.

https://github.com/manuelxmarquez/Vortice.Windows/commit/8c300acb18fed94ac139511a222a3f84ecfbbdad

One thing that is a bit weird though is the Default preset does not work. However, it also does not work in the C++ project either. So that may be some other bug.

**Comment by amerkoleci** [comment]
Thanks!
I've started collection of samples here, feel free to add some: https://github.com/amerkoleci/Vortice.Windows.Samples

P. S: Somehow I've updated solution to vs2022 preview

**Comment by manuelxmarquez** [comment]
I'll keep that in mind as I test other cases. I have VS 2022 Preview so that's not a problem.

**Comment by mrcoffeeee** [comment]
Hi guys, thank you so much for your effort. I tested the new nuget package (Vortice.XAudio2 2.0.20) and all the reverb presets work now despite the "Default"-preset. This is the only one which results in no sound.
