### ISSUE TITLE
Headless?

### ISSUE THREAD

**Issue by dbruning** [amerkoleci/Vortice.Windows#129]
**Is your feature request related to a problem? Please describe.**
I would like to write unit tests which output rasterised 3D scenes. Generally unit test frameworks don't like to have to instantiate windows, so I wonder if it's possible to use Vortice.Windows without a window at all. 
As a specific request, it would be great to see a sample in this repo which renders a scene without requiring a window, either in a unit test (e.g. xunit) or a console app.

**Describe the solution you'd like**
To be able to use Vortice.Windows to render a Direct3D scene without needing a Window handle, via a unit test

**Describe alternatives you've considered**
[This stack exchange question](https://gamedev.stackexchange.com/questions/51526/directx11-without-window-attached) talks about initializing with D3D11CreateDevice, which requires no window, and then creating an offscreen render target & calling ID3D11DeviceContext::Flush to put the work to the GPU. 

**OS and backend**
I specifically need it for Direct3D (I guess D3D10+ because that's the first version that separates the concept of "device" and "swap chain" according to that same stackexchange question).

I have used higher-level libraries like Monogame in the past, but I'm not super familiar with the use of Direct3D directly, so apologies if this is not a good question/suggestion!

**Comment by amerkoleci** [comment]
This was something I had in mind to do, will prepare Direct3D11 (if possible Direct3D12) example of offscreen rendering.

**Comment by dbruning** [comment]
Awesome, thankyou

**Comment by amerkoleci** [comment]
Here you go,
You can run the Direct3D11 example and press "P" and it will take Screenshot.jpg otherwise if you enable headless mode it will automatically capture Screenshot.jpg.

https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/HelloDirect3D11/Program.cs#L62

Hope it helps

**Comment by dbruning** [comment]
That works great, thankyou! Are you planning to push new nugets anytime soon?

**Comment by amerkoleci** [comment]
You can grab the package from nuget:
https://www.nuget.org/packages/Vortice.Direct3D11/1.9.29-beta

**Comment by dbruning** [comment]
Thanks!

**Comment by amerkoleci** [comment]
Nuget stable release 1.9.41 just landed.
