### ISSUE TITLE
D2D1_COMPOSITE_MODE renaming is horrible

### ISSUE THREAD

**Issue by andrew-boyarshin** [amerkoleci/Vortice.Windows#135]
E.g. `DestinationInationIn` for `D2D1_COMPOSITE_MODE_DESTINATION_IN`. To be determined if SharpGen is to blame.

**Comment by andrew-boyarshin** [comment]
I don't think it's SharpGen's fault. Unlike SharpDX, Vortice extensively uses `<naming />` mapping directive, which defines high-priority renaming rules. `DEST` and `DST` both match for `DESTINATION` part, the longest one is used. That's how we get `DestinationInation`.

**Comment by amerkoleci** [comment]
Fixed in latest commit.

**Comment by andrew-boyarshin** [comment]
I was thinking more along the lines of `NoShortNameExpand` as `NamingRule`, but this will work too. I'll build the packages and check if Avalonia requires more fixes.
