### ISSUE TITLE
Proposal: unblock property generation

### ISSUE THREAD

**Issue by andrew-boyarshin** [amerkoleci/Vortice.Windows#136]
I propose removing `property="false"` from the bindings. Now the bindings are inconsistent: sometimes they use generated properties, sometimes they block them. There is no definitive rule at the moment. If someone consumes bindings, they have to check which variant is used in each case. I believe small deviations from C++ headers in situations like these are justified. Moreover, I want the mappings files to be as simple as possible. They are slowly getting as complex as SharpDX ones.

**Comment by amerkoleci** [comment]
I agree, some job has started, will keep this issue updated once done.
