### ISSUE TITLE
Access violation in IDirect3DDevice9.CreateTexture trying to create a shared texture

### ISSUE THREAD

**Issue by lellid** [amerkoleci/Vortice.Windows#139]
Trying to create a shared texture with 
`IDirect3DDevice9.CreateTexture((int width, int height, int levels, Usage usage, Format format, Pool pool, IntPtr sharedHandleRef)` results in an access violation. Same code with SharpDX works properly. In SharpDX, the sharedHandleRef argument is given as a ref argument, but here in Vortice it is given by value. I guess this could be the reason for the access violation.

**Comment by amerkoleci** [comment]
This has been fixed with https://github.com/amerkoleci/Vortice.Windows/commit/35d8492561ca85ad9064e423d7bce2be69d02e54, please try it and see if it works properly.

**Comment by lellid** [comment]
Yes, it works now. Thanks!!!
