### ISSUE TITLE
Name property of ID3D12Object can't settable.

### ISSUE THREAD

**Issue by longlongago-k** [amerkoleci/Vortice.Windows#140]
ID3D12Object.Name.set() does not make sense.
User can call ID3D12Object.Name = "text";
But it does not work and ID3D12Object.Name always returns string.empty.

To instantly avoid this problem, I temporary use following extension.
``` C#
        public static void SetName(this ID3D12Object obj, string name)
        {
            var strPtr = Marshal.StringToHGlobalUni(name);
            int size = System.Text.Encoding.Unicode.GetByteCount(name);
            obj.SetPrivateData(CommonGuid.DebugObjectName, size, strPtr);
            Marshal.ZeroFreeGlobalAllocUnicode(strPtr);
        } 
```

**Comment by amerkoleci** [comment]
That's because ID3D12Object doesn't have GetName method support, i thought it would work with GetPrivateData but it seams it doesn't work, i will remove the Name property getter at this point.

**Comment by longlongago-k** [comment]
Thank you for the answer. I'll wait for the future support.

**Comment by amerkoleci** [comment]
Actually just fixed it with the commit: https://github.com/amerkoleci/Vortice.Windows/commit/8e9e6e3bbf6764ac3d3fbd4ad0f3c6dd2eb13167
