### ISSUE TITLE
Add example for IDxcIncludeHandler

### ISSUE THREAD

**Issue by manuelxmarquez** [amerkoleci/Vortice.Windows#142]
It took me a while to get IDxcIncludeHandler working. It looks like a sample was partially started but not working and HelloDirect3D12 was failing to compile the shaders. I managed to get it working and you can check the following commit as a reference for someone trying to implement it: https://github.com/manuelxmarquez/Vortice.Windows/commit/5862641b8d71313147bffb64fc4ffaffee0af66b

Let me know if you want me to submit a pull request or you can just copy this part to get the current sample callback method to be invoked
```
    public class ShaderIncludeHandler : CallbackBase, IDxcIncludeHandler
    {
        public Result LoadSource(string fileName, out IDxcBlob includeSource)
        {
            return Result.Ok;
        }
    }
```

**Comment by amerkoleci** [comment]
Same applies here @andrew-boyarshin, seams that the callback subclass doesn't get handle automatically as you can see here: https://github.com/manuelxmarquez/Vortice.Windows/commit/5862641b8d71313147bffb64fc4ffaffee0af66b#diff-f6bc4bcc14707dc071d869eef52fd5b27b468230d4930b13b1f03f96b21da14dR44

**Comment by manuelxmarquez** [comment]
Sorry, that was my first attempt. I later discovered it could be simplified to this https://github.com/manuelxmarquez/Vortice.Windows/commit/7ca1f72790f6f013c7c845a439f95f1e41ba5906

**Comment by manuelxmarquez** [comment]
When I was digging through the code I rewrote the classes because I thought the problem was here:
https://github.com/SharpGenTools/SharpGenTools/blob/0f77606717479d020c785f7ad435c95e0c738ba4/SharpGen.Runtime/MarshallingHelpers.cs#L22-L41

If the class derives from `CppObject` then the shadow is not used. It seems inheriting from `CallbackBase` instead gets around the problem.

**Comment by amerkoleci** [comment]
With next commit I'm updating to DX Compiler release for April 2021, stay tuned

**Comment by andrew-boyarshin** [comment]
Yeah, `CppObject` is for unmanaged impls, `CallbackBase` is for managed impls.
