### ISSUE TITLE
GlyphRun.GlyphIndices should be ushort[] instead of short[]

### ISSUE THREAD

**Issue by zgabi** [amerkoleci/Vortice.Windows#145]
In the `GlyphRun` class the `GlyphIndicies` property is `short[]` currenty:
https://github.com/amerkoleci/Vortice.Windows/blob/f619875c852d8fc3377d3849396c3c1d4e74a798/src/Vortice.Direct2D1/DirectWrite/GlyphRun.cs#L14

It should be `ushort[]`:
https://docs.microsoft.com/en-us/windows/win32/api/dwrite/ns-dwrite-dwrite_glyph_run

The `IDWriteFontFace.GetGlyphRunOutline` method is already receives an `ushort[]`, so it is not possible to pass directly the array. (I know that it is quite easy to cast a `short[]` to `ushort[]` with casting first to object, but it would be better if the `GlyphRun` property were `ushort[]`. )

Background:
In the `IDWriteTextRenderer.DrawGlyphRun` callback the received parameters can be passed directly to the `IDWriteFontFace.GetGlyphRunOutline`. Except this `GlyphIndicies` array, which type does not match:
See: https://docs.microsoft.com/en-us/windows/win32/directwrite/how-to-implement-a-custom-text-renderer
DrawGlyphRun/2, code sample.

**Comment by amerkoleci** [comment]
Nice catch, commit https://github.com/amerkoleci/Vortice.Windows/commit/40f1f6f550ccb11f23311e30baa717290d6e91f4 includes FIX.
