### ISSUE TITLE
Dxc DLLs not copied to the output directory in UWP

### ISSUE THREAD

**Issue by Aminator** [amerkoleci/Vortice.Windows#15]
The issue is that in UWP native DLLs only get copied automatically when they are in the `runtimes/win-(x64 or x86)/native` folder in the NuGet package. So what you can do is put the DLLs in those folders (like you had earlier) and for .NET Core 3.0 add that additional directory with `SetDllDirectory`, so you don't even need a .targets file.

Ideally this is something that either should be done automatically by .NET Core 3.0 or the DLLs should be copied next to the executable. We would have to contact the .NET Core team for that, but for now the above solution suffices.

**Comment by amerkoleci** [comment]
Hi @Aminator ,
UWP is not my primary target, even if some support is there.

Feel free to submit any PR.

Thanks
