### ISSUE TITLE
Some methods just return null on failure, with no way to get the HRESULT

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#150]
First, this is great project, thank you for your hard work :-)

Question: I notice for some creation methods there doesn't appear to be a way to get the HRESULT if the method fails, they just return `null`.

ID3D12Device.CreateRootSignature
ID3D12Device.CreateCommandSignature
ID3D12Device.CreateComputePipelineState
ID3D12Device.CreateGraphicsPipelineState
ID3D12Device.CreatePlacedResource
ID3D12Device.CreateReservedResource
(There may be more, these are just the ones I noticed.)

Is this just an oversight and there should be an Result-returning overload? 'cause if so I can do a pull request :-)

**Comment by amerkoleci** [comment]
It was oversight, commit https://github.com/amerkoleci/Vortice.Windows/commit/7481411e43659c6e4d25c52b705a7eadcee2cfc2 fixes this.

Thanks
