### ISSUE TITLE
Can not create root signature directly from blob

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#154]
The native [ID3D12Device::CreateRootSignature](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createrootsignature) method allows for the creation of a root signature from a serialized blob. I see from the Vortice.Windows source code that the public CreateRootSignature overloads always call D3D12SerializeRootSignature to get the blob and then passes that to the (internal) native method.

The reason it's useful to be able to pass in a blob directly is twofold:
* The serialized root signature can be saved to disk and then reloaded.
* Compiled shaders can include a serialized root signature (if defined in the shader) -- in this case passing in the shader bytecode blob extracts the root signature.

Would it be possible to add an extra CreateRootSignature overload that takes a blob instead of a `RootSignatureDescription`?

**Comment by amerkoleci** [comment]
Nice catch, commit: https://github.com/amerkoleci/Vortice.Windows/commit/5c1aa5fe9ebdf65c52abd2a24a0ba663d7e4197e fixes this.

Thanks
