### ISSUE TITLE
ID2D1Bitmap1 and ID2D1BitmapRenderTarget: extra Release

### ISSUE THREAD

**Issue by andrew-boyarshin** [amerkoleci/Vortice.Windows#155]
Is there a need for `ReleaseBitmap` and `ReleaseColorContext`? SharpDX doesn't do this. Narrowed this down while debugging Avalonia.

**Comment by amerkoleci** [comment]
If I persist the value shouldn't manually release it?
https://github.com/amerkoleci/Vortice.Windows/blob/a624505759f75cc6b46ac9e9058a90dd0fc58167/src/Vortice.Direct2D1/Mappings.xml#L433

**Comment by andrew-boyarshin** [comment]
Yeah, mistake was actually calling `Release`, not `Dispose`. Next SharpGen 2.0 beta will contain the code to generate all that boilerplate for persistent properties.
