### ISSUE TITLE
Direct3D12: Some enum naming issues

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#160]
Here's some enum values I found that look like they're named incorrectly (all in Vortice.Direct3D12 namespace):

`HeapFlags.DenyRtDomainShaderTextureS`
`HeapFlags.DenyNonRtDomainShaderTextureS`
`HeapFlags.AllowOnlyNonRtDomainShaderTextureS`
`HeapFlags.AllowOnlyRtDomainShaderTextureS`
"TextureS" should be "Textures", see https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_heap_type

`LogicOp.CopyInverseErted`
`LogicOp.InverseErt`
`LogicOp.AndInverseErted`
`LogicOp.OrInverseErted`
"InverseErted" should be "Inverted", see https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_logic_op

`RaytracingGeometryFlags.NoDuplicateAnyhitInverseOcation`
Should be RaytracingGeometryFlags.NoDuplicateAnyhitInvocation, see https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_raytracing_geometry_flags

`StencilOperation.InverseErt`
Should be StencilOperation.Invert, see https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_stencil_op

**Comment by amerkoleci** [comment]
Fixed now, thanks!
