### ISSUE TITLE
Direct3D12: Span<T> or ReadOnlySpan<T> overloads

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#161]
I'm writing a D3D12 game engine using Vortice.Windows and I'm trying to avoid garbage collection, which means avoiding memory allocations. Some D3D12 APIs currently accept arrays, which must be allocated on the heap (right?)

Would it be possible to add some overloads that take a Span<T> or ReadOnlySpan<T> instead?

i.e. for these methods:
ID3D12CommandQueue.UpdateTileMappings()
ID3D12Device.CopyDescriptors()
ID3D12Device.GetCopyableFootprints()

I can create a pull request for this if you'd prefer.

**Comment by amerkoleci** [comment]
Hi, sure, feel free to submit PR.
