### ISSUE TITLE
Double initialization of Subresource field

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#165]
Very minor issue: `Subresource` is initialized twice in the `ResourceTransitionBarrier` constructor.

https://github.com/amerkoleci/Vortice.Windows/blob/f619875c852d8fc3377d3849396c3c1d4e74a798/src/Vortice.Direct3D12/ResourceTransitionBarrier.cs#L19-L22

**Comment by amerkoleci** [comment]
Fixed with https://github.com/amerkoleci/Vortice.Windows/commit/ea4e029b417a4ec2a4bec5c3cc7e2ed97fc2ed4c

Thanks
