### ISSUE TITLE
SetEventOnCompletion should accept a null waitHandle parameter

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Windows#166]
The documentation for ID3D12Fence::SetEventOnCompletion states that hEvent can be null, in which case "this API will not return until the specified fence value(s) have been reached." See https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-seteventoncompletion

But this doesn't work in Vortice.Windows (it throws a `NullReferenceException`).
https://github.com/amerkoleci/Vortice.Windows/blob/f619875c852d8fc3377d3849396c3c1d4e74a798/src/Vortice.Direct3D12/ID3D12Fence.cs#L10

**Comment by amerkoleci** [comment]
You can do:
SetEventOnCompletion(value, IntPtr.Zero) but will add overload.

Thanks

**Comment by amerkoleci** [comment]
Fixed with https://github.com/amerkoleci/Vortice.Windows/commit/ea4e029b417a4ec2a4bec5c3cc7e2ed97fc2ed4c

Thanks

**Comment by paulbartrum** [comment]
> You can do: SetEventOnCompletion(value, IntPtr.Zero)

Ah, you're right, I didn't notice that. Thanks!
