### ISSUE TITLE
Unable to enable DirectXDebugLayer

### ISSUE THREAD

**Issue by roy-t** [amerkoleci/Vortice.Windows#170]
I'm trying to enable the DirectX Debug Layer to get helpful messages while developing my application.

I create my device like this
```
D3D11CreateDevice(null, DriverType.Hardware, DeviceCreationFlags.Debug, null, out var device, out var context);
```

Which should be enough to enable the debug layer and get some output in the console. However, I got nothing in my console output. I've read that sometimes Visual Studio doesn't want to output these messages in a managed project. But I also do not see the messages in RenderDoc or other tools. 

To make sure I'm not getting any messages I'm now trying to retrieve them via the I3D11InfoQueue:

```
this.DebugDevice = device.ID3D11Device.QueryInterface<ID3D11Debug>();
this.DebugInfoQueue = this.DebugDevice.QueryInterface<ID3D11InfoQueue>();this.DebugInfoQueue.PushEmptyStorageFilter();
```

I then log the messages like this

```
public void LogMessages(ILogger logger)
{
    var stored = this.DebugInfoQueue.NumStoredMessages;

    for(ulong i = 0; i < stored; i++)
    {
        var message = this.DebugInfoQueue.GetMessage(i);
        logger.Write(
            SeverityToLevel(message.Severity),
            "{@id}{@category} {@description}",
            message.Id, message.Category, message.Description);
    }

    this.DebugInfoQueue.ClearStoredMessages();
}
```

and to make sure there is at least something to log I call 
```
this.DebugDevice.ReportLiveDeviceObjects(ReportLiveDeviceObjectFlags.Summary | ReportLiveDeviceObjectFlags.Detail);
```

Right before calling the log method, which should have at least something to report as I'm drawing a DearImGui window on screen. But  this.DebugInfoQueue.NumStoredMessages is always 0.

Unfortunately I haven't got a clue why nothing is showing up, inspecting the DebugInfoQueue gives a few suspect values, for example the message count limit is `0`. However the `NumMessagedDeniedByMessageCountLimit` is also always 0. MuteDebugOutput is set to True, but no matter what I do I can't change it.

![image](https://user-images.githubusercontent.com/623634/130198843-eea9be61-a1a3-421c-92b2-5ba3135b8731.png)

I have the Windows 10 SDK (10.0.19041.0) and 'Graphics Tools' feature installed
![image](https://user-images.githubusercontent.com/623634/130200135-ecbb74ae-8fc4-46d8-8ab6-dc4346c8a284.png)

**Comment by amerkoleci** [comment]
You need to enable unmanaged debug in your executable, otherwise nothing will get prompted in visual studio Output window

**Comment by roy-t** [comment]
Ok this is weird, so that does give me the output of the debug layer in Visual Studio's output window, so the debug layer works. But still nothing appears in the DebugInfoQueue and it also seems that the ReportLiveDeviceObjects call doesn't prompt more messages.

**Comment by amerkoleci** [comment]
Are you sure you have live objects being leaked? I suggest you to use the IDXGI debug layer as well, I suggest you this code: https://github.com/walbourn/directx-vs-templates/blob/master/d3d11game_win32_dr/DeviceResources.cpp

Otherwise if you have patience I can prepare an example at beginning of next week.

**Comment by amerkoleci** [comment]
This blog helps as well: https://walbourn.github.io/dxgi-debug-device/

**Comment by roy-t** [comment]
Maybe I misunderstood what ReportLiveDeviceObjects does, I'll try to generate some real errors to see if the queue. Thanks for all the other links as well, and the super swift response! I'll try to figure this out later today or tomorrow (unfortunately I ran out of time for today :( ).

**Comment by roy-t** [comment]
I found the problem its the interaction between renderdoc and my application:

```
RDOC 015676: [14:48:41]     d3d11_device.cpp( 836) - Warning - Returning a dummy ID3D11Debug that does nothing. This ID3D11Debug will not work!
RDOC 015676: [14:48:41]     d3d11_device.cpp( 782) - Warning - Returning a dummy ID3D11InfoQueue that does nothing. RenderDoc takes control of the debug layer.
RDOC 015676: [14:48:41]     d3d11_device.cpp( 787) - Warning - If you want direct access, enable API validation and query for GUID {3fc4e618-3f70-452a-8b8f-a73accb58e3d}. This will return the real ID3D11InfoQueue - be careful as it is unwrapped so you should not call QueryInterface on it.
```

**Comment by amerkoleci** [comment]
Glad you find the issue, never thought the issue would be with renderdoc integration

**Comment by amerkoleci** [comment]
Is your project open source?

**Comment by roy-t** [comment]
That's so cool to hear. I've been stuck on MonoGame with the MiniRTS so I started working on a replacement using Vortice. Because its mostly a mess right now I haven't made the repository public yet. Not much to see :)

**Comment by roy-t** [comment]
For completeness here's a class that uses the DebugInfoQueue to write the log messages to the console (or your own logger). With this you don't have to enable mixed debugging support, which makes everything a lot faster. It also detects correctly if RenderDoc or another profiler is intercepting your calls to the debug layer.

```
using Vortice.Direct3D11;
using Vortice.Direct3D11.Debug;

namespace Mini.Engine.Debugging
{
    public sealed class DebugLayerLogger
    {
        private readonly ID3D11InfoQueue DebugInfoQueue;

        public DebugLayerLogger(ID3D11Device device)
        {
            var debugDevice = device.QueryInterface<ID3D11Debug>();
            this.DebugInfoQueue = debugDevice.QueryInterface<ID3D11InfoQueue>();
            this.DebugInfoQueue.PushEmptyStorageFilter();

            var annotations = device.ID3D11DeviceContext.QueryInterface<ID3DUserDefinedAnnotation>();
            if(annotations.Status)
            {
                Console.WriteLine("A Microsoft Direct3D profiling tool (RenderDoc, Visual Studio Profiler, ...) is attached to the current context. Log messages from the DirectX Debug Layer might not be available");
            }
        }

        public void LogMessages()
        {
            var stored = this.DebugInfoQueue.NumStoredMessages;
            for(ulong i = 0; i < stored; i++)
            {
                var message = this.DebugInfoQueue.GetMessage(i);

                // The description string is zero terminated which leads to weird output in the visual studio output window
                this.Console.WriteLine(UnterminateString(message.Description));
            }

            this.DebugInfoQueue.ClearStoredMessages();
        }

        private static string UnterminateString(string message)
        {
            if(message.EndsWith('\0'))
            {
                return message[0..^1];
            }
            return message;
        }
    }
}
```
