### ISSUE TITLE
[Minor] MessageId enum lists 'Roy' instead of 'Destroy'

### ISSUE THREAD

**Issue by roy-t** [amerkoleci/Vortice.Windows#178]
Today I had an extremely confusing experience. My name is Roy, and all of a sudden my log was filled with output like 'DestinationRoyPixelShader ...' (I output messages from the ID3D11InfoQueue.

After a bit of a search I figured out that in the MessageId enum in the generated file `Enumerations.cs`  values like these are generated:

```
/// <summary>
/// No documentation.
/// </summary>
/// <unmanaged>D3D11_MESSAGE_ID_DESTROY_CONTEXT</unmanaged>
/// <unmanaged-short>D3D11_MESSAGE_ID_DESTROY_CONTEXT</unmanaged-short>
DestinationRoyContext = unchecked((int)2097227),
```

Looks like something truncates 'Destroy' to 'Roy'.  I tried rebuilding the latest master on my PC to see if the issue was already fixed. But unfortunately NuGet was giving me some issues which I haven't looked into yet.

This issue is of course extremely minor, but I thought I'd mention it anyway.

**Comment by amerkoleci** [comment]
Latest nuget should have this issue fixed? Did you tried it? I will gladly fix otherwise

**Comment by amerkoleci** [comment]
It happens with latest version as well, will fix it now and release new nuget package.

Thanks

**Comment by roy-t** [comment]
Ah great to hear, thanks again!

**Comment by roy-t** [comment]
@amerkoleci btw I've made the next iteration of MiniEngine (very early WIP) public now. Its all based on Vortice.Windows, so if you're looking for inspiration on how your work is used, this could be useful. You also mentioned you liked following the previous iterations :): https://github.com/roy-t/MiniEngine3

**Comment by amerkoleci** [comment]
Thanks, will keep and eye on it, add mention in Readme as well
