### ISSUE TITLE
D3DCompiler no compatible with SharpGen.Runtime?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#183]
Hey @amerkoleci 

Trying to install D3DCompiler in .NET Framework 4.7.2 and it fails with

```
Unable to find a version of 'SharpGen.Runtime' that is compatible with 'Vortice.D3DCompiler 1.9.130 constraint: SharpGen.Runtime (>= 2.0.0-beta.9)', 'Vortice.Direct3D11 1.9.130 constraint: SharpGen.Runtime (>= 2.0.0-beta.9)', 'Vortice.DirectX 1.9.130 constraint: SharpGen.Runtime (>= 2.0.0-beta.9)', 'Vortice.DXGI 1.9.130 constraint: SharpGen.Runtime (>= 2.0.0-beta.9)'.
```

It should support .NET Framework right?

Downgrading to eg 1.8.48 works fine (edit: ok normal started having this dependency from 1.9.24-beta)

**Comment by amerkoleci** [comment]
There shouldn't be any issues with net framework, will try later and see if it happens

**Comment by andrew-boyarshin** [comment]
SharpGen.Runtime supports .NET Framework 4.5+ and .NET Standard 1.1+, it definitely should work.

**Comment by SuRGeoNix** [comment]
@andrew-boyarshin True, no issues with SharpGen.Runtime by itself. If you install it first then D3DCompiler can be installed as well. There is something wrong with D3DCompiler dependencies (not sure if it should point to Runtime.COM? or a possible bug with version tag -beta.9?)

**Comment by amerkoleci** [comment]
I just created new console app targetting .NET 4.7.2 and run the command:
`
Install-Package Vortice.D3DCompiler -Version 1.9.130
`

No issues found

**Comment by SuRGeoNix** [comment]
Steps to reproduce, open WinForms .NET 4.7.2 and try to install the package from the GUI package manager (I will check if that works with CLI)

**Comment by SuRGeoNix** [comment]
Hey, just to let you know that I've tested on another machine before posting it here just to make sure it wasn't my installation.
However, if you think that is not related with Vortice feel free to close it! Not sure why it doesn't happens to you (nuget clear cache maybe to make sure?)

**Comment by amerkoleci** [comment]
This has nothing to do with Vortice.Windows, please add NuGet.config file in your repo with this content https://github.com/amerkoleci/Vortice.Windows/blob/main/NuGet.Config

**Comment by SuRGeoNix** [comment]
I've tried all those. I had some issues with a specific package of mine (opened an issue here https://developercommunity.visualstudio.com/t/NuGet-package-install-crashes-Visual-Stu/1522395) but I'm not sure if that has to do anything with Vortice package. That's why I've tried that also from another machine to double check. Still same issue. 

No worries, let's leave it for now and might someone else will re-open it.

**Comment by SuRGeoNix** [comment]
Finally found the related [NuGet issue](https://github.com/NuGet/Home/issues/2944)

It will not combine stable with prerelease versions, it's more like a decision rather a bug.

If you have a large dependencies you can recursively bypass this by using Install-Package with -IncludePrerelease option or might IgnoreDependecies option on VS.

Ideally, when you have a stable version you should try to reference to stable versions as well.

**Comment by pubpy2015** [comment]
Confirm: can not install Vortice.D3DCompiler from **NuGet Package Manager** but can install from **Package Manager Console** as @SuRGeoNix solution:
video:


https://user-images.githubusercontent.com/59004953/133819118-6ad7e43a-ac07-46d5-acc1-8de2850fffa2.mp4
