### ISSUE TITLE
LUID (64-bit value) support for x86 platforms?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#185]
Hey @amerkoleci, 

I didn't have much time to look in to it but I've noticed with adapter.Description.Luid on x86 will be 0. I guess there are other places with [LUIDs](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/drivers/ff549708(v=vs.85)) as well. Is this possible to support them on x86 platforms?

Regards,
John

**Comment by amerkoleci** [comment]
Not sure why, LUID is platform indipendent and its size is 8.
Need more info please.

**Comment by SuRGeoNix** [comment]
Sure. part of my code that lists the GPU adapters

```c#
if (CreateDXGIFactory1(out IDXGIFactory2 factory).Failure)
   throw new InvalidOperationException("Cannot create IDXGIFactory1");
                
for (int adapterIndex = 0; factory.EnumAdapters1(adapterIndex, out IDXGIAdapter1 adapter).Success; adapterIndex++)
   Utils.Log($"[#{adapterIndex+1}] {adapter.Description.Description} ({adapter.Description.DeviceId} | {adapter.Description.Luid})");
```

x64 output
```
[11.40.01.364] [#1] Radeon RX 580 Series (26591 | 53204)
[11.40.01.368] [#2] Radeon RX 580 Series (26591 | 84355)
[11.40.01.369] [#3] Microsoft Basic Render Driver (140 | 65451)
```

x86 output
```
[11.40.26.998] [#1] Radeon RX 580 Series (26591 | 0)
[11.40.27.001] [#2] Radeon RX 580 Series (26591 | 0)
[11.40.27.003] [#3] Microsoft Basic Render Driver (140 | 0)
```

As you can see the last value is 0 which is the LUID.

**Comment by amerkoleci** [comment]
Same issue was present on SharpDX: https://github.com/sharpdx/SharpDX/issues/475

Will FIX it.

**Comment by SuRGeoNix** [comment]
Nice. It seems similar issues could exist with SIZE_T etc https://github.com/sharpdx/SharpDX/issues/692

**Comment by amerkoleci** [comment]
Issue is with AdapterDescription, can you try quickly with Description1 please?

**Comment by SuRGeoNix** [comment]
Output for
```
Utils.Log($"[#{adapterIndex+1}] {adapter.Description.Description} ({adapter.Description.DeviceId} | {adapter.Description1.Luid}) | {adapter.Description1.DedicatedVideoMemory}");
```

x64
```
[12.02.04.787] [#1] Radeon RX 580 Series (26591 | 53204) | 8568401920
[12.02.04.790] [#2] Radeon RX 580 Series (26591 | 84355) | 8568401920
```

x86
```
[12.02.26.646] [#1] Radeon RX 580 Series (26591 | 53204) | -1073741824
[12.02.26.649] [#2] Radeon RX 580 Series (26591 | 84355) | -1073741824
```

Description1.Luid works. Description1.DedicatedVideoMemory doesn't.

**Comment by amerkoleci** [comment]
Just use the code from here:
https://github.com/helix-toolkit/helix-toolkit/commit/49a86a333efbee4ae0808438b88b0e317cd7f0db

It should work with latest commit also the AdapterDescription

**Comment by amerkoleci** [comment]
Please report if it works? Thank you!

**Comment by SuRGeoNix** [comment]
No it returns 3221225472 instead of 8568401920.

**Comment by amerkoleci** [comment]
Wait for CI build and grab packages from here: https://github.com/amerkoleci?tab=packages

Version beta3

**Comment by SuRGeoNix** [comment]
Still not available. I will also have to add GitHub packages authentication. Wouldn't be easier to send me an email the updated package (DXGI ?)

**Comment by SuRGeoNix** [comment]
OK, I've compiled it from my PC now and still the same problem.

```
x64
adapter.Description1.DedicatedVideoMemory	0x00000001feb77000 	| 8568401920	System.UIntPtr

x86
adapter.Description1.DedicatedVideoMemory	0xc0000000			| 3221225472	System.UIntPtr
```

**Comment by amerkoleci** [comment]
Version 2.1.0-beta6 from nuget should fix this issue.

**Comment by SuRGeoNix** [comment]
Hi @amerkoleci, just update and re-tested. Same results for PointerSize (DedicatedVideoMemory) on x86.
