### ISSUE TITLE
CSSetUnorderedAccessViews - Possible incorrect parameter passing.

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#203]
Will submit a pull request.

As per https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-cssetunorderedaccessviews

The accessviews and offsets need to be passed in an array.  At the moment from what I understand, they arent.

I will create a pull request to:

* Make the interfaces protected.
* Create Wrapper functions to handle the additional field handling
* Ensure that ID3D11UnorderedAccessView unorderedAccessView[], int uavInitialCount[] are optional

Detected the bug when using compute shaders within my code, the views weren't being passed to the shader.

@amerkoleci let me know if its ok.

Will follow similar approach to sharpdx (in terms of function coding only)

EDIT: SOrry, wrong link!

https://github.com/sharpdx/SharpDX/blob/ab36f12303e24aa60fe804866617716b6ded95db/Source/SharpDX.Direct3D11/DeviceContext.ComputeShaderStage.cs

**Comment by amerkoleci** [comment]
You linked wrong link, I'm doing something similar here: https://github.com/amerkoleci/Vortice.Windows/blob/main/src/Vortice.Direct3D11/ID3D11DeviceContext.cs#L119

**Comment by h1cks** [comment]
No, theser are the CSUnsetUnorderedAccessViews, not the output merger.

Updated link, my bad.

**Comment by h1cks** [comment]
Checked CSSetUnorderedAccessView and its ok as it marshals the parameters within the generated code. 

For CSUnsetUnorderedAccessViews it doesnt martial at the moment.

I've pushed my code to my branch, includes test code, so you might just want to copy my code if that's ok

https://github.com/h1cks/Vortice.Windows/commit/c7e4bd8820420b88c9e227770d01ebfb7a9870cc

**Comment by amerkoleci** [comment]
Ok thanks, tomorrow I will add the missing bits

**Comment by amerkoleci** [comment]
Commit https://github.com/amerkoleci/Vortice.Windows/commit/96e70f246b4bdda7a3ea845cb14f3824adbe591c fixes this
