### ISSUE TITLE
UnorderedAccessviews tested - working

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows#206]
Just a heads up that the changes you made in beta 4 are working for both 

CSSetUnorderedAccessView and CSSetUnorderedAccessViews.  Also confirm that Texture3d is working also.

![image](https://user-images.githubusercontent.com/17155885/141258324-71fc87ac-de3f-4915-aa5a-6f3d32b5ebe1.png)

I have some other issue around my buffers with combining them, but that's my issue.  Feel free to close, but can confirm 3d textures are working in conjunction with compute buffers.

**Comment by amerkoleci** [comment]
Maybe next time open discussion :D Good job.

**Comment by h1cks** [comment]
should look like this but my perlin noise is not working correctly atm.

![image](https://user-images.githubusercontent.com/17155885/141258640-48221a7b-5543-48cb-a7d2-55782b2b7663.png)

**Comment by h1cks** [comment]
> Maybe next time open discussion :D Good job.

thought this would be faster to bring to your attention, as your library is getting closer to maturity!  Good work!
