### ISSUE TITLE
ResourceAliasingBarrier does not accept nulls

### ISSUE THREAD

**Issue by RawRCoder** [amerkoleci/Vortice.Windows#209]
Code: https://github.com/amerkoleci/Vortice.Windows/blob/f658e9b520c73a63965d5dc85c209985e7b6a761/src/Vortice.Direct3D12/ResourceAliasingBarrier.cs#L13-L14

Docs: https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_resource_aliasing_barrier

Docs claim, that one can use aliasing barrier with one or both resources missing (NULLs). Right now I have to use a somewhat wacky approach with `new ID3D12Resource(IntPtr.Zero)`. Perhaps it would be better just to allow nulls in `ResourceAliasingBarrier.ctor` as well as in `ResourceBarrier.BarrierAliasing`.

Same issue might also be there for other kinds of ResourceBarrier

**Comment by amerkoleci** [comment]
This has been fixed with commit: https://github.com/amerkoleci/Vortice.Windows/commit/943c9297b692ca6f12306fe4a94c0e1b95dc0151 beta5 will contain the fix.
