### ISSUE TITLE
Add type safety to StateObject API

### ISSUE THREAD

**Issue by Aminator** [amerkoleci/Vortice.Windows#21]
Currently when using a `StateObjectDescription` you have to provide a pointer for `PSubobjects` and the count for `NumSubobjects` instead of simply a `StateSubObject[]` or ideally `Span<StateSubObject>`.

`StateSubObject` could also be improved, but in this case the `Description` field can be of any type, so maybe just accept an `object` as well, though that would incur boxing.

**Comment by amerkoleci** [comment]
Initial marshalling landed (https://github.com/amerkoleci/Vortice.Windows/commit/2d32b8ba46bafbcadefce149c942c67060099717), StateSubObject accepts all types allowed now, need just to marshal some other stuff.

**Comment by Aminator** [comment]
Looks good. 👍
