### ISSUE TITLE
[Question] IMMNotificationClient interface?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#213]
Hi @amerkoleci, I'm trying to replace NAudio with Vortice, so far so good! I'm having some trouble to create a IMMNotificationClient to handle the events (confused with that IntPtr in the constructor). What am I missing?

**Comment by amerkoleci** [comment]
Can you show me how you create IMMNotificationClient using NAudio? So I can add the missini API.

Thanks

**Comment by SuRGeoNix** [comment]
I just implement the interface here and I'm good to go

https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.Wasapi/CoreAudioApi/Interfaces/IMMNotificationClient.cs

Here is my code https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/AudioMaster.cs

**Comment by amerkoleci** [comment]
I see, thanks!

Commit https://github.com/amerkoleci/Vortice.Windows/commit/8d9be436e1a2b8bedf051f721ea6312dbc301964 maps IMMNotificationClient  as callback interface

**Comment by SuRGeoNix** [comment]
Nice, I will try to build it and tested

**Comment by SuRGeoNix** [comment]
Currently failed but I'm still looking...

```csharp
deviceEnum.RegisterEndpointNotificationCallback(this);

InvalidOperationException: Operation is not valid due to the current state of the object.

This exception was originally thrown at this call stack:
    SharpGen.Runtime.MarshallingHelpers.ToCallbackPtr<TCallback>(SharpGen.Runtime.ICallbackable)
    Vortice.MediaFoundation.IMMDeviceEnumerator.RegisterEndpointNotificationCallback(Vortice.MediaFoundation.IMMNotificationClient) in Interfaces.cs
    FlyleafLib.AudioMaster.AudioMaster() in AudioMaster.cs
    FlyleafLib.Master.Master() in Master.cs
```

**Comment by SuRGeoNix** [comment]
This line complains

```
client_ = SharpGen.Runtime.MarshallingHelpers.ToCallbackPtr<Vortice.MediaFoundation.IMMNotificationClient>(client);
```

**Comment by amerkoleci** [comment]
You have to include CallbackBase as well, similar to this example: https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/HelloDirect3D12/ShaderIncludeHandler.cs#L13

**Comment by SuRGeoNix** [comment]
It would be great if we can avoid this somehow tho!

**Comment by SuRGeoNix** [comment]
It seems that it misses the AudioSessions as well?
