### ISSUE TITLE
XAudio2.CreateMasteringVoice not deviceId?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#214]
Hi @amerkoleci, is it possible to changed the audio endpoint device to xaudio2?

```csharp
public IXAudio2MasteringVoice CreateMasteringVoice(
            int inputChannels = DefaultChannels,
            int inputSampleRate = DefaultSampleRate,
            AudioStreamCategory category = AudioStreamCategory.GameEffects)
{
    return CreateMasteringVoice(inputChannels, inputSampleRate, 0, null, null, category);
}
```

**Comment by SuRGeoNix** [comment]
If I am not missing something I've added this and testing it

```csharp
public IXAudio2MasteringVoice CreateMasteringVoice(
            int inputChannels,
            int inputSampleRate,
            int flags, string device,
            AudioStreamCategory category = AudioStreamCategory.GameEffects)
{
    return CreateMasteringVoice(inputChannels, inputSampleRate, flags, device, null, category);
}
```

**Comment by amerkoleci** [comment]
https://github.com/amerkoleci/Vortice.Windows/commit/1290df003433e80d0bcca34d7a01fff95636e16a fixes this, thanks!

**Comment by SuRGeoNix** [comment]
Nice, I can change devices just fine now. 
I managed to get rid of NAudio that it was causing a lot of issues! Low latency, better performance, less memory.

Hope you will have soon new releases so I can include them!

Thanks

**Comment by amerkoleci** [comment]
2.1.0-beta10 is being compiled, wait for nuget release and update!
