### ISSUE TITLE
Missing HRESULT for IDXGIOutputDuplication::AcquireNextFrame

### ISSUE THREAD

**Issue by schillc** [amerkoleci/Vortice.Windows#215]
First of all thanks for being the spiritual successor of SharpDX and in many cases even better.

When porting one of my projects from SharpDX to Vortice I noticed that there is no HRESULT return value for [IDXGIOutputDuplication::AcquireNextFrame](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-acquirenextframe) and instead it returns void 

SharpDX implementation (TryAcquireNextFrame) : https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.DXGI/OutputDuplication.cs

I'm not familiar with SharpGen so it would be great to see this fixed in a future release. Thanks!

**Comment by amerkoleci** [comment]
Thanks! This has been fixed with https://github.com/amerkoleci/Vortice.Windows/commit/2117c21f7bca8ff05529a19c87d690a4d37478b4

**Comment by schillc** [comment]
Thanks, works great!
