### ISSUE TITLE
Memory Leak ID2D1GeometrySink

### ISSUE THREAD

**Issue by schillc** [amerkoleci/Vortice.Windows#216]
When porting SharpDX code to Vortice I noticed that the ID2D1GeometrySink interface is missing a Dispose method and therefore leaks memory.

`    var innerGeo = _context.Device.Factory.CreatePathGeometry(); // ID2D1DeviceContext`
`    var innerSink = innerGeo.Open();`
`    innerGeo.Dispose();`
`    innerSink.Dispose(); // <- missing`

The [documentation ](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1geometrysink) states that one should use [SafeRelease ](https://docs.microsoft.com/en-us/windows/win32/medfound/saferelease) however I think the System.IDisposable approach would be more suited.

**Comment by amerkoleci** [comment]
You can call Release as ID2D1GeometrySink  subclass IUnknown, otherwise I could make ID2D1GeometrySinkNative public so you can call Dispose on it.

**Comment by schillc** [comment]
> otherwise I could make ID2D1GeometrySinkNative public so you can call Dispose on it.

That would be much appreciated

**Comment by amerkoleci** [comment]
Commit https://github.com/amerkoleci/Vortice.Windows/commit/afbedaa8bdcffc21602f9558d05fea5379c189a9 fixes this!

**Comment by schillc** [comment]
Thanks, just updated to 2.1.1-beta2 and can now dispose ID2D1GeometrySink like this:
` ((ID2D1GeometrySinkNative) innerSink).Dispose(); `

Doesn't look as pretty as a Dispose on ID2D1GeometrySink, but I guess that's not possible because only ID2D1GeometrySinkNative implements IDisposable.

```
    /// <unmanaged>HRESULT ID2D1PathGeometry::Open([Out] ID2D1GeometrySink** geometrySink)</unmanaged>
    /// <unmanaged-short>ID2D1PathGeometry::Open</unmanaged-short>
    public unsafe ID2D1GeometrySink Open()
    {
      IntPtr zero = IntPtr.Zero;
      // ISSUE: cast to a function pointer type
      // ISSUE: function pointer call
      Result result = (Result) __calli((__FnPtr<int (IntPtr, void*)>) (IntPtr) this[17U])((void*) this.NativePointer, (IntPtr) &zero);
      ID2D1GeometrySinkNative geometrySinkNative = zero != IntPtr.Zero ? new ID2D1GeometrySinkNative(zero) : (ID2D1GeometrySinkNative) null;
      result.CheckError();
      return (ID2D1GeometrySink) geometrySinkNative;
    }
```
