### ISSUE TITLE
D3D11CreateDevice with context Memory Leak (VRAM)

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#217]
Hi @amerkoleci and happy new year!

I come up with this one that you might want to check:-

```csharp
public void NoMemoryLeak()
{
	D3D11.D3D11CreateDevice(null, DriverType.Hardware, DeviceCreationFlags.BgraSupport, new FeatureLevel[] { FeatureLevel.Level_11_0 }, out ID3D11Device device);
	System.Threading.Thread.Sleep(500);
	device.Dispose();
}

public void MemoryLeak()
{
	D3D11.D3D11CreateDevice(null, DriverType.Hardware, DeviceCreationFlags.BgraSupport, new FeatureLevel[] { FeatureLevel.Level_11_0 }, out ID3D11Device device, out _, out ID3D11DeviceContext context);
	System.Threading.Thread.Sleep(500);
	context.ClearState();
	context.Flush();
	context.Dispose();
	device.Dispose();
}
```

And did some test with task manager and the dedicated GPU memory column in details Tab:

```csharp
Task.Run(() =>
{
    while (true)
        MemoryLeak();
});
```

Update:
I solved my memory leak issue but I think it was not related it with the above. I just used FlipDiscard instead of Discard. Might FFmpeg messed with my Device not sure yet.

**Comment by amerkoleci** [comment]
Can you confirm if this is still a thing?

**Comment by SuRGeoNix** [comment]
I've tested with the latest build, did you have any changes? Does it happen at your system?

**Comment by SuRGeoNix** [comment]
Just to let you know that I've retested and still happens, it seems that the code behind it keeps a reference of the context.
I solved my issue by using the other method without the context but I think it is an important issue and needs to be resolved.

**Comment by amerkoleci** [comment]
Can you try with 2.1.1-beta5 release?

**Comment by SuRGeoNix** [comment]
Looks ok now
