### ISSUE TITLE
XAudio2Create compatibility issue?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#218]
Hi @amerkoleci,

I had a [user](https://github.com/SuRGeoNix/Flyleaf/pull/109) that had an issue with XAudio2 on Windows 10 (1809).  Any ideas why ProcessorSpecifier.UseDefaultProcessor while ProcessorSpecifier.DefaultProcessor works fine? It seems - by looking at the [header file](https://github.com/amerkoleci/Vortice.Windows/blob/main/src/native/include/xaudio2redist.h) - like a compatibility issue:

```c
// This value indicates that XAudio2 will choose the default processor by itself. The actual value chosen
// may vary depending on the hardware platform.
#define XAUDIO2_USE_DEFAULT_PROCESSOR 0x00000000

// This definition is included for backwards compatibility. New implementations should use
// XAUDIO2_USE_DEFAULT_PROCESSOR instead to let XAudio2 select the appropriate default processor for the hardware platform.
#define XAUDIO2_DEFAULT_PROCESSOR Processor1
```

I don't get it how this causes issues on Win 10 machine (as it uses xAudio2.9). You might want to consider using the microsoft's nuget [package](https://docs.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-redistributable#supported-platforms)? And possible review whether by default you should set the DefaultProcessor instead of UseDefaultProcessor if the dll/sdk not support it?

**Comment by amerkoleci** [comment]
At the begining I had xaudio2 redist (from nuget) as part of Vortice.XAudio2, that caused big binary size and I removed, I would probably move back to XAudio2 SDK headers, meanwhile send PR with the FIX if you want or wait for me to go back to XAudio2 headers from Windows 10 SDK.

**Comment by amerkoleci** [comment]
Commit https://github.com/amerkoleci/Vortice.Windows/commit/d2781f4405b86419095fb90802f384ce443bd40b switch to Windows SDK, can you try and tell me if it works for you?

**Comment by SuRGeoNix** [comment]
Unfortunately, it does not happen on my system, I cannot easily reproduce it. @MycroBeat might be able though. I'm not familiar with XAudio2 at all so I cannot help you much either :(

**Comment by MycroBeat** [comment]
@SuRGeoNix If you want to reproduce, try to install a Windows 10 1809 on a virtual machine. Should detect the bug.

@amerkoleci Hi. I'm sorry, but I'm not so familiar with c ++ or git. Can you release an alpha/beta build to nuget to test? Or something to test and solve this problem?

**Comment by SuRGeoNix** [comment]
@MycroBeat yes probably wait for a beta release and just update nuget packages at my solution to test it. No time currently to install it on vm :(

**Comment by amerkoleci** [comment]
Wait for CI build and version 2.1.1-beta2 should appear on nuget, thanks!

**Comment by MycroBeat** [comment]
After upgrading to 2.1.1-beta2, audio seems to work on Windows 10 1809. I also test the 2.1.1-beta2 release on Windows 10 1607, Windows 10 1507 and the problem seems to be fixed.

**Comment by amerkoleci** [comment]
> After upgrading to 2.1.1-beta2, audio seems to work on Windows 10 1809. I also test the 2.1.1-beta2 release on Windows 10 1607, Windows 10 1507 and the problem seems to be fixed.

Nice, thanks!
