### ISSUE TITLE
ID3D11VideoProcessorEnumerator::GetVideoProcessorCaps is missing

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#219]
[msdn](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11videoprocessorenumerator-getvideoprocessorcaps)

**Comment by amerkoleci** [comment]
ID3D11VideoProcessorEnumerator.VideoProcessorCaps is property
