### ISSUE TITLE
D3D11 Video Processor minor suggestions

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#220]
Hi @amerkoleci, I was messing around with video processor today and I kept some notes that you might want to check.

1) Missing VideoProcessorProcessorCaps Enum [d3d11.h]( https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_video_processor_processor_caps)

```csharp
public enum VideoProcessorProcessorCaps
{
	DeinterlaceBlend	        = 0x1,
	DeinterlaceBob	                = 0x2,
	DeinterlaceAdaptive 	        = 0x4,
	DeinterlaceMotionCompensation	= 0x8,
	InverseTelecine	                = 0x10,
	FrameRateConversion             = 0x20
}
```

2) Typos on VideoProcessorFilter / VideoProcessorFilterCaps with SaturateUration / StereoAdjacencyUstment

3) Possible confusion with VideoProcessorColorSpace and how it converts bool to int in the backend (possible just use int or enums with the names provided by [msdn](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_video_processor_color_space))

```csharp
Usage 			= false, 	// 0 - Playback, 1 - Processing
RgbRange 		= true, 	// 0 - Full (0-255), 1 - Limited (16-235) (RGB)
YCbCrMatrix 	        = true, 	// 0 - BT.601, 1 - BT.709
YCbCrXvYCC 		= true, 	// 0 - Conventional YCbCr, 1 - xvYCC
NominalRange 	        = 0 		// 0 - driver defaults, 2 - Full range [0-255], 1 - Studio range [16-235] (YUV)
```

**Comment by amerkoleci** [comment]
> Hi @amerkoleci, I was messing around with video processor today and I kept some notes that you might want to check.
> 
> 1. Missing VideoProcessorProcessorCaps Enum [d3d11.h](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_video_processor_processor_caps)
> 
> ```cs
> public enum VideoProcessorProcessorCaps
> {
> 	DeinterlaceBlend	        = 0x1,
> 	DeinterlaceBob	                = 0x2,
> 	DeinterlaceAdaptive 	        = 0x4,
> 	DeinterlaceMotionCompensation	= 0x8,
> 	InverseTelecine	                = 0x10,
> 	FrameRateConversion             = 0x20
> }
> ```
> 
> 2. Typos on VideoProcessorFilter / VideoProcessorFilterCaps with SaturateUration / StereoAdjacencyUstment
> 3. Possible confusion with VideoProcessorColorSpace and how it converts bool to int in the backend (possible just use int or enums with the names provided by [msdn](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_video_processor_color_space))
> 
> ```cs
> Usage 			= false, 	// 0 - Playback, 1 - Processing
> RgbRange 		= true, 	// 0 - Full (0-255), 1 - Limited (16-235) (RGB)
> YCbCrMatrix 	        = true, 	// 0 - BT.601, 1 - BT.709
> YCbCrXvYCC 		= true, 	// 0 - Conventional YCbCr, 1 - xvYCC
> NominalRange 	        = 0 		// 0 - driver defaults, 2 - Full range [0-255], 1 - Studio range [16-235] (YUV)
> ```

1) The enum is present, VideoProcessorProcessorCaps:
```
public enum VideoProcessorProcessorCaps
{
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BLEND</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BLEND</unmanaged-short>
	DeinterlaceBlend = 1,
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BOB</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BOB</unmanaged-short>
	DeinterlaceBob = 2,
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_ADAPTIVE</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_ADAPTIVE</unmanaged-short>
	DeinterlaceAdaptive = 4,
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_MOTION_COMPENSATION</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_MOTION_COMPENSATION</unmanaged-short>
	DeinterlaceMotionCompensation = 8,
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_INVERSE_TELECINE</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_INVERSE_TELECINE</unmanaged-short>
	InverseErseTelecine = 0x10,
	/// <unmanaged>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_FRAME_RATE_CONVERSION</unmanaged>
	/// <unmanaged-short>D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_FRAME_RATE_CONVERSION</unmanaged-short>
	FrameRateConversion = 0x20
}

```

2: Ok will FIX
3: Will dig.

Please, if you can, submit PR in the future :)

**Comment by amerkoleci** [comment]
Just side request, would you be able to submit D3D11 Video example maybe?
I'm collecting samples here: https://github.com/amerkoleci/Vortice.Windows.Samples

Thanks

**Comment by SuRGeoNix** [comment]
For the samples yes, let me know if you want something specific and I will try to make a sample. Now generally, I try to avoid PRs as I'm not familiar with your design/implementation and I don't want to mess it up :)

**Comment by amerkoleci** [comment]
Don't worry, commit https://github.com/amerkoleci/Vortice.Windows/commit/6d263942736abf74b2d1b27c49bd4377b95a24d5 fixes your issues, you can use it as reference for your next PR in case :)

**Comment by SuRGeoNix** [comment]
No idea why I couldn't find the VideoProcessorProcessorCaps earlier. Another type in there InverseErseTelecine => InverseTelecine.

Thanks!
