### ISSUE TITLE
Exception of XAudio2

### ISSUE THREAD

**Issue by jhdevelp** [amerkoleci/Vortice.Windows#226]
Hello,
I describe my problem allready here.
https://github.com/EvergineTeam/Feedback/issues/113

I have also tried project - Vortice.Windows.Samples-main  but result is same.

Please, would you reccommed me some solution ?

Thank you in advance.

**Comment by amerkoleci** [comment]
I need to know which version of Vortice.XAudio you're using? There where recent changes with XAudio2 bindings

**Comment by jhdevelp** [comment]
![xaudio2_ver](https://user-images.githubusercontent.com/98220167/150927820-d47e9317-f48f-439d-abad-9e5bcccfd246.png)

**Comment by amerkoleci** [comment]
Still I don't see Vortice.XAudio2 version there

**Comment by jhdevelp** [comment]
I'am so sorry. Now it's correct.

Version - 2.1.0-beta7

![xaudio2_ver](https://user-images.githubusercontent.com/98220167/150996028-3b67d68e-3460-406d-adfa-ad8d39990e37.png)

**Comment by amerkoleci** [comment]
This was known bug and fixed with one of the latest beta release, Evergine probably need to target 2.1.1-beta9 or you can reference [2.1.1-beta9](https://www.nuget.org/packages/Vortice.XAudio2/2.1.1-beta9)
