### ISSUE TITLE
IDXGIDevice1::SetMaximumFrameLatency() missing.

### ISSUE THREAD

**Issue by Steph55** [amerkoleci/Vortice.Windows#228]
Thank you for your nice library! One detail:

Maybe I don't know where to look, but IDXGIDevice1::SetMaximumFrameLatency() seems to be missing from Vortice...

And this is important for multi-swapchains for a single device.

**Comment by amerkoleci** [comment]
Hi,
Its present, but actually its property, so you need to call IDXGIDevice1.MaximumFrameLatency = value;
Will change it to method in next release.

Thanks!

**Comment by amerkoleci** [comment]
Fixed with commit: https://github.com/amerkoleci/Vortice.Windows/commit/4f13421941cd59f21d77c0dcf9aad2a39754fe5d

**Comment by Steph55** [comment]
Hi, a property makes a lot of sense too, but we just have to be aware of it!

Thanks a lot!

Le mar. 1 févr. 2022 à 06:26, Amer Koleci ***@***.***> a
écrit :
