### ISSUE TITLE
Incorrect Free in BuildRaytracingAccelerationStructureInputs

### ISSUE THREAD

**Issue by CAMongrel** [amerkoleci/Vortice.Windows#23]
Hi and thank you for your great efforts so far!

There's an incorrect Marshal.FreeHGlobal in BuildRaytracingAccelerationStructureInputs:
```
internal void __MarshalFree()
{
    if (Union.pGeometryDescs != IntPtr.Zero)
    {
        Marshal.FreeHGlobal(Union.pGeometryDescs);
    }
}
```

The Union is being declared as such:
```
internal unsafe struct Union
{
    [FieldOffset(0)]
    public long InstanceDescs;

    [FieldOffset(0)]
    public IntPtr pGeometryDescs;
}
```

When using the Inputs structure in a top level acceleration structure scenario, you set the instances, when using it for bottom level acceleration scenarios, you set the geometry field, but never both (hence the union).

Setting the InstanceDescs to something other than zero will cause a crash when the runtime decides to call the Free method, making the BuildRaytracingAccelerationStructureInputs unusable in TopLevelAS cases. 
(Note: The InstanceDescs points to GPU memory, whereas the pGeometryDescs points to host memory)

I've worked around this by accepting the memory leak and commented out the Marshal.Free() call, but that's obviously not a solution. Generally I'm unsure how to fix this except by letting the developer handle this manually somehow.

**Comment by amerkoleci** [comment]
This has been fixed now, I plan to rework the logic and handle better scenario.
