### ISSUE TITLE
HelloDirect3D11 ScreenCapture

### ISSUE THREAD

**Issue by deccer** [amerkoleci/Vortice.Windows#235]
Hi :)

I am using Vortice.Windows obviously and tried adding capture from backbuffer and couldnt get it to work, the captured image keeps looking messed up (as if the pitch is wrong or something) then I checked the examples of this repo and saw that you also capture the backbuffer in the HelloDirect3D11 example, but funny enough, it also produces an odd output.

I am not sure whats wrong, tried various things but none worked out. I also tried older versions down to 1.9.117 as well, but same kaput result :)

(btw the api in 2.x is neat to use, i like it a lot)

![image](https://user-images.githubusercontent.com/15695435/156227313-ab9432b6-fbee-4924-8bc4-b272a2705b2e.png)

It should look like the actual triangle (unskewed :D) like you see in the window when running it

**Comment by amerkoleci** [comment]
Hi,
I saw that issue and not sure what breaked the api, will fix it as soon as I understand what caused the issue

**Comment by deccer** [comment]
not sure if it helps, but using plain GDI Bitmap works tho. also the staging texture looks alright in RenderDoc.

```cs
[DllImport("msvcrt.dll", EntryPoint = "memcpy", CallingConvention = CallingConvention.Cdecl, SetLastError = false)]
private static extern IntPtr CopyMemory(IntPtr dest, IntPtr src, UIntPtr count);

var mappedSubresource = deviceContext.Map(stagingTexture, 0, MapMode.Read, MapFlags.None);

using var bitmap = new System.Drawing.Bitmap(
    stagingTexture.Description.Width,
    stagingTexture.Description.Height,
    PixelFormat.Format32bppArgb);
var boundsRect = new Rectangle(0, 0, bitmap.Width, bitmap.Height);

var bitmapData = bitmap.LockBits(
    boundsRect,
    ImageLockMode.WriteOnly,
    bitmap.PixelFormat);

var sourcePtr = mappedSubresource.DataPointer;
var destPtr = bitmapData.Scan0;
for (var y = 0; y < bitmap.Height; y++)
{
    CopyMemory(destPtr, sourcePtr, new UIntPtr((uint)bitmap.Width * 4));

    sourcePtr = IntPtr.Add(sourcePtr, mappedSubresource.RowPitch);
    destPtr = IntPtr.Add(destPtr, bitmapData.Stride);
}

bitmap.UnlockBits(bitmapData);
deviceContext.Unmap(stagingTexture, 0);
```

**Comment by amerkoleci** [comment]
Yeah, issue is on wic/d2d1 side

**Comment by amerkoleci** [comment]
Thanks for bringing this, commit contains the fix: https://github.com/amerkoleci/Vortice.Windows/commit/15435d246de9056a35bd40884867f8a4e01ce4dc

Package 2.1.1-beta12 contains the fix.
