### ISSUE TITLE
[Help] Is there an easy way to convert Vortice.DirectWrite.FontWeight Windows.UI.Text.FontWeight

### ISSUE THREAD

**Issue by iloxmn** [amerkoleci/Vortice.Windows#236]
Just found out built in fontweight is a struct. Do I need to use a switch to convert this or there's something more simple?

**Comment by amerkoleci** [comment]
Please use [discussion](https://github.com/amerkoleci/Vortice.Windows/discussions) for this kind of question, anyway the answer is no but it isn't difficult to add that method by yourself, just cast the enum value to WinUI FontWeight value and you're good.
