### ISSUE TITLE
Vortice.Mathematics.Point not found

### ISSUE THREAD

**Issue by gerhard17** [amerkoleci/Vortice.Windows#237]
I have installed the latest nuget package Vortice.Direct2D1 2.1.1-beta9 which references Vortice.Mathematics 1.4.7

ID2D1RenderTarget.DrawLine(...) uses Vortice.Mathematics.Point as an argument type; but this type is not defined in Vortice.Mathematics 1.4.7

Is this Point type defined elsewhere in another assembly? Do I miss something or is this a bug in Vortice?

Regards, Gerhard

**Comment by amerkoleci** [comment]
Hi,
Nuget somehow orders packages in wrong order, you should use this one **2.1.1-beta12:**

https://www.nuget.org/packages/Vortice.Direct2D1/2.1.1-beta12

**Comment by gerhard17** [comment]
Oh, I overlooked that. It works now. 
Thank you!

Regards, Gerhard
