### ISSUE TITLE
Handle correct sign type of primitives

### ISSUE THREAD

**Issue by amerkoleci** [amerkoleci/Vortice.Windows#24]
I just committed the fix to avoid mapping from native UINT64 and UINT16 to C# long and short, instead of ulong and and ushort.
I was planning to fix the UINT32 map as well and map to uint instead of int as now. 

This commit shows the fix https://github.com/amerkoleci/Vortice.Windows/commit/ea17b5874bdd79486aa6a1e175eab7bc813dafb7

@Aminator @Sergio0694 do you find any issue with this one?

**Comment by Aminator** [comment]
For .NET usage using signed types everywhere is definitely easier as it avoids unnecessary casts. Also unsigned types are not CLS compliant, but that is only a small detail.

**Comment by amerkoleci** [comment]
I know, but I'm worried about overflow, fence ulong value is bigger than long, of course not sure when you reach maximum size

**Comment by amerkoleci** [comment]
https://github.com/mellinoe/veldrid uses uint for width, height etc, not sure which one  is better

**Comment by Aminator** [comment]
In my game engine I only use signed types and I've never encountered a problem with it. The maximum fence value with a long will be reached when the sun has already turned into a red giant, so...

**Comment by amerkoleci** [comment]
I agree :) will revert back to signed types and some cleanup then
