### ISSUE TITLE
[question] What's the difference with sharpdx?

### ISSUE THREAD

**Issue by emako** [amerkoleci/Vortice.Windows#240]
What's the difference with sharpdx?
Can Vortice provide the same 2D interface as sharpdx?
Can WPF be supported?
Thanks.

**Comment by amerkoleci** [comment]
Please use https://github.com/amerkoleci/Vortice.Windows/discussions for this kind of questions.

Anyway yes, it provides bindings for all stuff that SharpDX provided and more.

feel free to ask specific questions under discussions.
