### ISSUE TITLE
DWrite ColorGlyphRun.GlyphRunDescription is an intptr (fix inside)

### ISSUE THREAD

**Issue by miyu** [amerkoleci/Vortice.Windows#242]
I patched the DirectWrite support to (correctly?) marshal ColorGlyphRun.GlyphRunDescription at https://github.com/miyu/Vortice.Windows/commit/973dde97da97dff43e91099118acca7063199360

Prior, GlyphRunDescription was an IntPtr, which made it unusable from managed `IDWriteTextRenderer` implementations. Is this the correct direction for a fix PR? Or is there a simpler approach? (feel free to do this yourself if I'm getting in the way, else I'll happily take this to completion)

**Comment by amerkoleci** [comment]
Thanks!

This commit handles the marshal scenario: https://github.com/amerkoleci/Vortice.Windows/commit/0632d0055ececd1bab593032d7eec48f8cb0279b
