### ISSUE TITLE
IDWriteTextRenderer.DrawGlyphRun doesn't round-trip IDWriteTextLayout.SetDrawingEffect input

### ISSUE THREAD

**Issue by miyu** [amerkoleci/Vortice.Windows#243]
`IDWriteTextRenderer.DrawGlyphRun` has parameter `IUnknown clientDrawingEffect` that can be set via `IDWriteTextLayout.SetDrawingEffect(IUnknown drawingEffect, TextRange textRange)`.  This is useful for specifying custom effects on ranges of text (e.g. coloring, misc text effects)

An example managed drawing effect follows:

```
public class CustomDrawingEffect : CallbackBase, IUnknown {
  public Color4 Color { get; set; }
 }
```

However, `IDWriteTextRenderer.DrawGlyphRun` does not round-trip the managed reference. Instead, it creates a ComObject wrapping the shadow's native allocation, with no clear route to get the original managed object. Is this intentional?

# Solution 1: Change IDWriteTextRendererShadow.IDWriteTextRendererVtbl.DrawGlyphRun_ unmarshal

The autogenerated code is as follows:

```
clientDrawingEffect = clientDrawingEffect_ != System.IntPtr.Zero ? new SharpGen.Runtime.ComObject(clientDrawingEffect_) : null;
@this.DrawGlyphRun(clientDrawingContext, baselineOriginX, baselineOriginY, measuringMode, glyphRun, glyphRunDescription, clientDrawingEffect);                    
```

I think the autogenerated code should be as follows, though this would segfault if native drawing effects were used. It's also unclear to me how to get SharpGen to emit this code. I'll investigate that further tomorrow. If you have any pointers to existing code/bindings that'd be appreciated.

```
clientDrawingEffect = clientDrawingEffect_ != System.IntPtr.Zero ? ToShadow<CppObjectShadow>(clientDrawingEffect_).Callback : null;
```

# Solution 2: Expose API to reinterpret ComObjects as shadow-boxed objects.

Here is my workaround utility, which I'd be happy to clean up and submit as a PR:

```
if (clientDrawingEffect is ComObject comobject) {
  var callbackable = NativeMarshalUtils.GetShadowCallbackable(comobject.NativePointer);
  if (callbackable is CustomDrawingEffect cde) {
    clientDrawingEffect = cde;
  }
}

public class NativeMarshalUtils : CppObjectShadow {
  protected override CppObjectVtbl Vtbl => throw new NotImplementedException();
  public static ICallbackable GetShadowCallbackable(IntPtr ptr) {
    var shadow = ToShadow<CppObjectShadow>(ptr);
    return shadow.Callback;
  }
}
```

**Comment by miyu** [comment]
@amerkoleci if either of these solutions sound desirable, I'd happily volunteer to further investigate and submit a PR. Let me know.

**Comment by amerkoleci** [comment]
Doesnt something like this work?

https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/AdvancedTextRenderingApp/Program.cs#L30

**Comment by miyu** [comment]
I don't believe so. `brush = comObject.QueryInterfaceOrNull<ID2D1SolidColorBrush>();` works because ID2D1SolidColorBrush is a native intptr-backed ComObject, so QueryInterfaceOrNull can meaningfully Activator.CreateInstance(typeof(ID2D1SolidColorBrush), nativeptr).

My custom drawing effect is not a native intptr-backed ComObject (note CallbackBase inherits from DisposeBase and ICallbackable), but QueryInterface only works with ComObjects, so I can't use it.

I've tried implementing both CallbackBase and ComObject separately, plus a few other attempt. I've found a few approaches that successfully pass managed objects into SetDrawingEffect and read them back from DrawGlyphRun's IUnknown clientDrawingEffect, but none are ergonomic. 

My ideal would be `SetDrawingEffect(new CustomManagedObject(), textRange)` and in `DrawGlyphRun` a simple `if (clientDrawingEffect is CustomManagedObject obj)`. I haven't found a way to do this.

# Simple CallbackBase attempt (doesn't work)

```
      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      [Shadow(typeof(CustomDrawingEffectShadow))]
      public interface ICustomDrawingEffect : IUnknown {
         public float4? Color { get; set; }
      }

      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      public class CustomDrawingEffect : CallbackBase, ICustomDrawingEffect {
         public float4? Color { get; set; }
      }

      private class CustomDrawingEffectShadow : CppObjectShadow
      {
         private static CustomDrawingEffectVtbl VtblInstance = new CustomDrawingEffectVtbl();

         protected override CppObjectVtbl Vtbl => VtblInstance;

         public class CustomDrawingEffectVtbl : CppObjectVtbl {
            public CustomDrawingEffectVtbl() : base(0) { }
         }
      }

```

QueryInterfaceOrNull<CustomDrawingEffect> doesn't work, since this doesn't inherit ComObject which QueryInterface requires.

# Simple ComObject attempt (doesn't work)

```
      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      [Shadow(typeof(CustomDrawingEffectShadow))]
      public interface ICustomDrawingEffect : IUnknown {
         public float4? Color { get; set; }
      }

      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      public class CustomDrawingEffect : ComObject, ICustomDrawingEffect, IUnknown {
         public CustomDrawingEffect() {
            // Releasd on dispose
            NativePointer = Marshal.GetIUnknownForObject(this);
         }

         public float4? Color { get; set; }
      }

      private class CustomDrawingEffectShadow : CppObjectShadow
      {
         private static CustomDrawingEffectVtbl VtblInstance = new CustomDrawingEffectVtbl();

         protected override CppObjectVtbl Vtbl => VtblInstance;

         public class CustomDrawingEffectVtbl : CppObjectVtbl {
            public CustomDrawingEffectVtbl() : base(0) { }
         }
      }

```

Here, if we `comobject.QueryInterface<CustomDrawingEffect>()` the internal QueryInterface will succeed and find a non-null cppObjectPtr, but then crash at `(T) Activator.CreateInstance(typeof(T), cppObjectPtr)`; it'll try to `new CustomDrawingEffect(ptr)` which doesn't exist.

I've found two workarounds, which don't feel particularly amazing:

# Workaround 1: Marshal.GetObjectForIUnknown

At the start of DrawGlyphRun, cast `IUnknown clientDrawingEffect` to a ComObject, take its NativePointer, and get the original managed object from the IUnknown.

```
if (clientDrawingEffect is ComObject comobject) {
  clientDrawingEffect = (CustomDrawingEffect)Marshal.GetObjectForIUnknown(comobject.NativePointer);
```

# Option 2: Wrap an inner-COM-object allocation.

This works with QueryInterface but is still not very ergonomic. 

```
            textLayout.SetDrawingEffect(
               new CustomDrawingEffect { Color = (0, 0, 0, 1) },
               new TextRange(0, text.Length)
            );


         public void DrawGlyphRun(IntPtr clientDrawingContext, float baselineOriginX, float baselineOriginY, MeasuringMode measuringMode, GlyphRun glyphRun, GlyphRunDescription glyphRunDescription, IUnknown clientDrawingEffect) {
            if (clientDrawingEffect is ComObject comobject) {
               var cde = comobject.QueryInterface<CustomDrawingEffect>();
               clientDrawingEffect = cde;
            }
```

The code follows:

```
      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      [Shadow(typeof(CustomDrawingEffectShadow))]
      public interface ICustomDrawingEffect : IUnknown {
         public float4? Color { get; set; }
      }

      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      public class CustomDrawingEffect : ComObject, ICustomDrawingEffect, IUnknown {
         private readonly Inner inner;
         public CustomDrawingEffect() : this(new Inner()) { }

         public CustomDrawingEffect(IntPtr nativePtr) : this((Inner)Marshal.GetObjectForIUnknown(nativePtr)) { }

         private CustomDrawingEffect(Inner inner) {
            this.inner = inner;
            NativePointer = inner.NativePointer;
         }

         public float4? Color {
            get => inner.Color;
            set => inner.Color = value;
         }

         [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
         private class Inner : ComObject, ICustomDrawingEffect, IUnknown {
            public Inner() {
               NativePointer = Marshal.GetIUnknownForObject(this);
            }

            public float4? Color { get; set; }
         }
      }

      private class CustomDrawingEffectShadow : CppObjectShadow
      {
         private static CustomDrawingEffectVtbl VtblInstance = new CustomDrawingEffectVtbl();

         protected override CppObjectVtbl Vtbl => VtblInstance;

         public class CustomDrawingEffectVtbl : CppObjectVtbl {
            public CustomDrawingEffectVtbl() : base(0) { }
         }
      }
```

**Comment by miyu** [comment]
Apologies for the lengthy response, mostly documenting my work in case anyone tries to follow.

I'm unsure whether SharpGen supports this specific use-case. I'm still looking into that. Hopefully I'm either doing something wrong or we can tweak Mappings.xml to support this use case.

**Comment by amerkoleci** [comment]
Hi,
I managed somehow to workaround it using Marshal.GetIUnknownForObject, but .NET6 is giving me problem during runtime:

Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.'

So, I'm not sure how to workaround this issue!

**Comment by miyu** [comment]
I suspect `Marshal.GetIUnknownForObject` is actually creating a [COM Callable Wrapper (CCW)](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-callable-wrapper) for the underlying C# object (perhaps holding onto a gchandle), rather than somehow using the C# object itself as an IUnknown. I haven't verified the runtime code, but if this is true, the IUnknown received is of that CCW, not our object.

So, the IUnknown needs to be unboxed. Either Vortice.Windows or end-user-applications need to handle COM Wrapping and Unwrapping. Do you believe this is Vortice.Windows' job or end-user-applications' job?

If this is Vortice.Windows' job, we can solve this by:

1. Adding to `public partial class IDWriteTextLayout` an overload `SetDrawingEffect(object, TextRange)` which boxes the managed object as an IUnknown, then passes that to `SetDrawingEffect(IUnknown, TextRange)`.
2. Default-implementing IDWriteTextRenderer.DrawGlyphRun(..., IUnknown clientDrawingEffect) to attempt to unbox the IUnknown, then call IDWriteTextRenderer.DrawGlyphRun(..., object clientDrawingEffect). Either that, or providing an ManagedDWriteTextRendererBase abstract base class that does this.

If this is the end-users' job, here is the managed wrapper that I am now using. It is complicated, but perhaps the people who use Vortice.Windows are technically capable enough to do this themseles:

Usage:
```
public class CustomDrawingEffect : ComWrappedObjectBase {
  public float4? Color { get; set; }
}

var black = new CustomDrawingEffect { Color = (0, 0, 0, 1) };
textLayout.SetDrawingEffect(
  black.ComWrapper,
  new TextRange(0, text.Length)
);

public void DrawGlyphRun(IntPtr clientDrawingContext, float baselineOriginX, float baselineOriginY, MeasuringMode measuringMode, GlyphRun glyphRun, GlyphRunDescription glyphRunDescription, IUnknown clientDrawingEffect) {
  var customDrawingEffect = clientDrawingEffect.UnboxComWrappedManagedObjectOrNull<CustomDrawingEffect>();
  ...
```

Wrapper Code:

```

   [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
   [Shadow(typeof(ManagedComWrapperShadow))]
   public interface IManagedComWrapper : IUnknown {
      public object WrappedObject { get; }
   }

   [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
   public class ManagedComWrapper : ComObject, IManagedComWrapper, IUnknown {
      private readonly Inner inner;
      public ManagedComWrapper(object o) : this(new Inner(o)) { }

      public ManagedComWrapper(IntPtr nativePtr) : this((Inner)Marshal.GetObjectForIUnknown(nativePtr)) { }

      private ManagedComWrapper(Inner inner) {
         this.inner = inner;

         // Will be Marshal.Release() freed by ComObject on dispose.
         NativePointer = inner.NativePointer;
      }

      public Object WrappedObject => inner.WrappedObject;

      [Guid("8DD71D09-E84A-42F2-82A7-7B3E0955504A")]
      private class Inner : ComObject, IManagedComWrapper, IUnknown {
         public Inner(object wrappedObject) {
            NativePointer = Marshal.GetIUnknownForObject(this);
            WrappedObject = wrappedObject;
         }

         public object WrappedObject { get; }
      }
   }

   internal class ManagedComWrapperShadow : CppObjectShadow {
      private static CustomDrawingEffectVtbl VtblInstance = new CustomDrawingEffectVtbl();

      protected override CppObjectVtbl Vtbl => VtblInstance;

      public class CustomDrawingEffectVtbl : CppObjectVtbl {
         public CustomDrawingEffectVtbl() : base(0) { }
      }
   }

   public class ComWrappedObjectBase : IDisposable {
      private ManagedComWrapper comWrapper;

      public ComWrappedObjectBase() {
         comWrapper = new(this);
      }

      public ManagedComWrapper ComWrapper => comWrapper;

      public void Dispose() {
         comWrapper?.Dispose();
         comWrapper = null;
      }
   }

   public static class ComWrapperExtensions {
      public static T UnboxComWrappedManagedObjectOrNull<T>(this IUnknown unk) {
         var wrapper = ((ComObject)unk).QueryInterface<ManagedComWrapper>();
         return (T)wrapper?.WrappedObject;
      }
   }
```

**Comment by amerkoleci** [comment]
Whatever works, I tried your approach but the issue with GetIUnknownForObject call, we have to avoid that call and should probably work, need to try something else!

**Comment by miyu** [comment]
Odd, what's your `dotnet --version`? I'm on 6.0.201 and don't encounter that issue; Marshal.GetIUnknownForObject works just fine here.

**Comment by amerkoleci** [comment]
Same, I'm on 6.0.201 :)

**Comment by amerkoleci** [comment]
Which target platform you target? net6-windows?

**Comment by amerkoleci** [comment]
The issue was with trim analyzer, I just update the example to showcase the custom effects, take look here:
https://github.com/amerkoleci/Vortice.Windows/commit/9cbaea6d1c78bd8e06f36c0448cc9b21496f78df
