### ISSUE TITLE
DirectStorage NuGet package working?

### ISSUE THREAD

**Issue by stephtr** [amerkoleci/Vortice.Windows#245]
I tried to start with DirectStorage using the supplied sample [HelloDirectStorage](https://github.com/amerkoleci/Vortice.Windows/tree/main/src/samples/HelloDirectStorage). When cloning the whole code, it works. However, if I exchange the project reference `<ProjectReference Include="..\..\Vortice.DirectStorage\Vortice.DirectStorage.csproj" />` to the NuGet package via `<PackageReference Include="Vortice.DirectStorage" Version="2.1.4-beta" />`, the app crashes at [EnqueueRequest](https://github.com/amerkoleci/Vortice.Windows/blob/f1b969368e57ec70759b727176c8cd2e604f52e0/src/samples/HelloDirectStorage/Program.cs#L68) via a stack buffer overrun.
Should the NuGet package work? Is there anything inherently wrong?

**Comment by amerkoleci** [comment]
Hi, 
Should have fixed it now, can you try with new 2.1.5-beta version and tell me if it works?

Thanks

**Comment by stephtr** [comment]
Perfect, for me it's working now!
Thanks for your work!
