### ISSUE TITLE
DirectXCollision.h

### ISSUE THREAD

**Issue by Kharzette** [amerkoleci/Vortice.Windows#253]
I noticed basic BoundingSphere, Frustum and such are generated, but they are missing alot of functions, such as some of the flavours of contains and intersects that might be just raw functions rather than methods.

I had a look at it but I'm a total novice at SharpGen.  It looks really tricky with all that vectorcall and __m128 types and such.  Can SharpGen handle stuff like that?

**Comment by amerkoleci** [comment]
I'm not generating those types using SharpGen but handwritten, take look here:

https://github.com/amerkoleci/Vortice.Mathematics/blob/main/src/Vortice.Mathematics/BoundingFrustum.cs
