### ISSUE TITLE
Fxc shader compilation

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Windows#258]
Does Vortice support compiling shader model 5 ? So does it have Fxc integration? I see there are API's for Dxc, but that's not useful for Dx11.

**Comment by amerkoleci** [comment]
Please use https://github.com/amerkoleci/Vortice.Windows/discussions for those question:
Yes it has D3DCompiler support and it can be seen here: https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/HelloDirect3D11/D3D11GraphicsDevice.cs#L161
