### ISSUE TITLE
Any DLSS/FSR support on DX12?

### ISSUE THREAD

**Issue by orosbogdan** [amerkoleci/Vortice.Windows#282]
Hello,

Does Vortice.Windows offer and DLSS/FSR functionality ? If not, any plans to add it in the future ?

**Comment by amerkoleci** [comment]
You mean AMD libraries like FidelityFX? if yes then they are out of scope of the project, this project AIM is to provide bindings for directx libraries and other windows libs.

**Comment by orosbogdan** [comment]
Yes I meant AMD FSR/ Nvidia DLSS, I just wanted to know, thank you for the quick reply.
