### ISSUE TITLE
Typo in package description

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#29]
![image](https://user-images.githubusercontent.com/1189759/65101622-a3ec3980-d996-11e9-8ce8-5cbb61aa9dc3.png)

**Comment by amerkoleci** [comment]
That's not related to Vortice.Windows but to my game framework https://github.com/amerkoleci/vortice

**Comment by nathan-alden** [comment]
Oops; yeah. Sorry about that.
