### ISSUE TITLE
Vortice packages dependencies issue

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#291]
It seems that it requires the following packages

```
[SharpGen.Runtime](https://www.nuget.org/packages/SharpGen.Runtime/) (>= 2.0.0-ci.1062)
[SharpGen.Runtime.COM](https://www.nuget.org/packages/SharpGen.Runtime.COM/) (>= 2.0.0-ci.1062)
```

but their latest version is 2.0.0-beta.10

**Comment by amerkoleci** [comment]
You need this entry to your nuget config until new SharpGen release:

https://github.com/amerkoleci/Vortice.Windows/blob/main/NuGet.config#L6

**Comment by SuRGeoNix** [comment]
That will require everyone that uses my package to do it as well. I guess I will wait for the sharpgen release.

**Comment by amerkoleci** [comment]
I'm waiting for @andrew-boyarshin for new nuget release then I'll switch to official nuget package, patience, he plans to release them soon
