### ISSUE TITLE
[Feature Request] Support for DirectShow

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#292]
Just wondering if you have this in your plans. I think it would fits for Vortice purpose. 

I mainly interesting for [this](https://docs.microsoft.com/en-us/windows/win32/directshow/using-the-system-device-enumerator) to enumerate audio/video capture devices.

Update: It seems I can use IMMDeviceEnumerator for at least audio capture devices

**Comment by amerkoleci** [comment]
Please open a discussion instead of issue:

https://github.com/amerkoleci/Vortice.Windows/discussions

**Comment by SuRGeoNix** [comment]
I found out that is possible with the newest Media Foundation API with [MFEnumDeviceSources](https://docs.microsoft.com/en-us/windows/win32/medfound/audio-video-capture-in-media-foundation?redirectedfrom=MSDN). So, probably not really required to add DirectShow.

However, I'm having some trouble to enumerate with it:

```csharp
var attrs = MediaFactory.MFCreateAttributes(1);
attrs.Set(CaptureDeviceAttributeKeys.SourceType, CaptureDeviceAttributeKeys.SourceTypeVidcap);
var res = MediaFactory.MFEnumDeviceSources(attrs, out IntPtr vidCapsPtr, out int capsCount);
```

Trying to get the result devices from the IntPtr.

**Comment by amerkoleci** [comment]
https://github.com/amerkoleci/Vortice.Windows/commit/b8ec1490d366bfb66c17cac680c1f4b1c115d13b added improvements in this scenario. I've added also example that enumerates Audio/Video capture devices:

https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/MediaFoundation/EnumerateDevices/Program.cs#L29
