### ISSUE TITLE
ReportLiveDeviceObjects sometimes crashing

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Windows#296]
I've seen this issue a few times...
![VorticeCrashing](https://user-images.githubusercontent.com/4374176/172047918-cba059e8-3831-479e-b95a-011c40175527.png)
![VorticeCrashing2](https://user-images.githubusercontent.com/4374176/172047921-b9949068-8521-43f8-ac57-808db4a8b383.png)

Edit: Sry, at first I thought there were two different exception. But I think both images relate to the same exception. I just had different info on the screen in each.

**Comment by amerkoleci** [comment]
Need example to reproduce to track the issue.

Thanks
