### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by nathan-alden-sr** [amerkoleci/Vortice.Windows#30]
The following code:
```csharp
D3D11.D3D11CreateDevice(
    null,
    DriverType.Hardware,
    DeviceCreationFlags.BgraSupport | DeviceCreationFlags.Debug,
    new[] { FeatureLevel.Level_11_1, FeatureLevel.Level_11_0 },
    out ID3D11Device d).CheckError();

d.Dispose();
```
results in the following debug output after a call to `IDXGIDebug::ReportLiveObjects`:
```
DXGI WARNING: Live IDXGIFactory at 0x000001CDF07E4740, Refcount: 2 [ STATE_CREATION WARNING #0: ]
DXGI WARNING: 	Live IDXGIAdapter at 0x000001CDF1598D30, Refcount: 1 [ STATE_CREATION WARNING #0: ]
DXGI WARNING: Live                   IDXGIAdapter :      1 [ STATE_CREATION WARNING #0: ]
D3D11 WARNING: Live ID3D11Device at 0x000001CDF1725030, Refcount: 3 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
D3D11 WARNING: 	Live ID3D11Context at 0x000001CDF17584E0, Refcount: 1, IntRef: 1 [ STATE_CREATION WARNING #2097226: LIVE_CONTEXT]
D3D11 WARNING: Live                  ID3D11Context :      1 [ STATE_CREATION WARNING #422: LIVE_OBJECT_SUMMARY]
```
Is this a memory leak as it appears? I noticed this when testing my `D2DERR_RECREATE_TARGET` code; my app started consuming memory like crazy.

**Comment by nathan-alden-sr** [comment]
Looks like this static function is leaking the `ID3D11DeviceContext` ref:
```csharp
public static Result D3D11CreateDevice(
  IDXGIAdapter adapter,
  DriverType driverType,
  DeviceCreationFlags flags,
  FeatureLevel[] featureLevels,
  out ID3D11Device device)
{
  FeatureLevel featureLevel;
  ID3D11DeviceContext immediateContext;
  return D3D11.D3D11CreateDevice(adapter, driverType, flags, featureLevels, out device, out featureLevel, out immediateContext);
}
```
When I manually `d.ImmediateContext.Dispose();`, the debug output disappears.

**Comment by nathan-alden-sr** [comment]
There also seem to be many other memory leaks, presumably of the same type. It's time-consuming to track them down but I see them by merely initializing resources then immediately releasing them with `Dispose()` calls. Might be worth taking a look at all the factory methods that follow the above pattern.

**Comment by amerkoleci** [comment]
Will take look and fix it very soon, thanks for reporting

**Comment by nathan-alden-sr** [comment]
I discovered the other leak. I was executing this code:
```csharp
using var dxgiOutput1 = _dxgiSwapChain1.ContainingOutput.QueryInterfaceOrNull<IDXGIOutput1>();
```
Unfortunately, I did not realize that merely calling properties on some of these interfaces actually adds a ref to the underlying object. I think this violates the principle of least astonishment; usually, properties should not have these kinds of side effects. As it stands, I will have to decompile every property to see whether a ref is being added.

**Comment by amerkoleci** [comment]
That's the same as calling on native code, you have to use using on properties as well, fixing it for all props is difficult

**Comment by nathan-alden-sr** [comment]
I understand that, but native code doesn't have properties, and thus no conventions around their use. The actual native call is `HRESULT GetContainingOutput(IDXGIOutput **ppOutput);`, which is a method. Again, the issue here isn't regarding the native code at all, but rather the use of C# properties (which are almost always side-effect free) for stateful code.

**Comment by amerkoleci** [comment]
I can avoid property or not sure how can avoid leakage

**Comment by nathan-alden-sr** [comment]
I'm not expecting magic, for sure. :) I know that the caller has to release the object. I'm merely saying that by making the interface a _property_, it gives developers the wrong impression because properties are normally side-effect free. Making it a method might at least be a hint that the reference needs to be disposed.

**Comment by amerkoleci** [comment]
Some fixes has landed.

**Comment by nathan-alden-sr** [comment]
These changes appear to have fixed the live objects I was seeing after calling `IDXGIDebug::ReportLiveObjects`. Thank you very much!

I also saw you changed `ContainingOutput` to `GetContainingOutput()`. 👍 I think there are other properties in various areas that do the same thing (e.g., `IDXGIDevice.Adapter`).

**Comment by amerkoleci** [comment]
IDXGIDevice.Adapter is now persisted and release when IDXGIDevice is Disposed, if you see any other scenarios please report.
