### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Noemata** [amerkoleci/Vortice.Windows#31]
Initializers/Bootstrappers that support HoloLens.  HoloLens emulator would be a good start.

**Comment by amerkoleci** [comment]
Submit PR and I will gladly merge it

**Comment by Noemata** [comment]
I haven't implemented this.  I was requesting the feature.  I'll have a look at trying to implement your code, but use the SharpDX Holographic template as an example.  I've yet to see a third party library outside of Urho, Unity and WaveEngine implement HoloLens support.  Probably because it's non-trivial.  Would be nice to see an open this in your implementation since it appears to be the path forward for former SharpDX users.  That said, support for Mixed Reality is kind of crucial at present.

**Comment by Noemata** [comment]
Also, DirectX12GameEngine claims to support MR, but the initialization code is incomplete.  There are several missing steps to get this working in that code,  In particular, the way GraphicsDevice is initialized in needs to make use of HolographicSpace, but the order implemented precludes access when needed.  It's on the right track nonetheless.

**Comment by Aminator** [comment]
@Noemata I haven't had access to a HoloLens yet, so I could only try it with a Windows Mixed Reality headset a while back in DirectX12GameEngine. Once I get myself a HoloLens 2 (hopefully this year), I will work on support for that in addition to spatial interaction with hands and eyes. The UWP API does a great job of exposing these features.
