### ISSUE TITLE
DML: dll copying from /build/net461/Vortice.DirectML.props not working.

### ISSUE THREAD

**Issue by Axiverse** [amerkoleci/Vortice.Windows#317]
I've copied the folder and props structure from DirectStorage, however I'm not seeing the right dlls being loaded with the props in `~/.nuget\packages\vortice.directml\2.1.20-beta\build\net461`. When the props are directly copied in the build folder (one level above, with copy target src paths respectively changed) the right dlls are loaded. Do you know if there's something I'm missing and can I be sure that DirectStorage is actually using the dlls included and not ones that come preloaded with windows (if that is even an options)?

I'm not sure how these props are picked up. Is it a magic folder that's just picked up by the compiler?

**Comment by Axiverse** [comment]
@amerkoleci any ideas here?

**Comment by amerkoleci** [comment]
> @amerkoleci any ideas here?

Sorry, somehow I missed this one, I'll merge PR and let see what we can bring in the future to improve native library support.
