### ISSUE TITLE
RaytracingInstanceDescription Transform

### ISSUE THREAD

**Issue by diwot** [amerkoleci/Vortice.Windows#32]
The Property Transform in RaytracingInstanceDescription is only one float long. After reading the documentation (https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_raytracing_instance_desc) I would expect 12 floats in a 3x4 matrix.

**Comment by amerkoleci** [comment]
Thanks for reporting, fixed now
