### ISSUE TITLE
IMFMediaEngine support?

### ISSUE THREAD

**Issue by amwx** [amerkoleci/Vortice.Windows#320]
Are there any plans to support the MediaEngine related stuff in MediaFoundation? Based on some other posts it seems MF is only partially implemented but I'm not sure if that's because of time or if MF is too complicated? I'm trying to update some old SharpDX code and it seems all the MediaEngine related classes are missing along with the MediaEngineAttributes guids. The code is just a simple play video and render to texture, nothing fancy:

```C#
mt = device.QueryInterface<DeviceMultithread>();
mt.SetMultithreadProtected(true);
DXGIManager = new DXGIDeviceManager();
DXGIManager.ResetDevice(device);

//  This is as far as I can get

mediaEngineFactory = new MediaEngineClassFactory();
attr = new MediaEngineAttributes();
attr.VideoOutputFormat = 87;// DXGI.Format.B8G8R8A8_UNorm;
attr.DxgiManager = DXGIManager;

mediaEngine = new MediaEngine(mediaEngineFactory, attr, MediaEngineCreateFlags.None);
mediaEngineEx = mediaEngine.QueryInterface<MediaEngineEx>();

mediaEngine.PlaybackEvent += OnPlaybackCallback;
```

I'm not all that familiar with how the bindings are created but it looks like `MFmediaengine.h` is missing from the `mappings.xml` file. I tried adding that in myself but it led to a bunch of errors that I'm not sure how to resolve.

**Comment by amerkoleci** [comment]
Please next time use [Discussions](https://github.com/amerkoleci/Vortice.Windows/discussions) for those type of questions.
Anyway: 
Here is an example that show how to use media engine and play audio:

https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/MediaFoundation/AudioPlay/Program.cs
