### ISSUE TITLE
IDirect3DQuery9 not properly supported

### ISSUE THREAD

**Issue by this-is-your-do** [amerkoleci/Vortice.Windows#321]
Hi, something I came across the other day:

The IDirect3DQuery9 interface is not properly supported:
- (Minor) IDirect3DQuery9.Issue should take an argument of type Issue (already existing enum), not int.
- (Minor) IDirect3DQuery9.GetData should take a third argument of a new "GetData" enum type, not int.
- (Major) IDirect3DQuery9.GetData is meant to return either S_OK or S_FALSE (or bool), not void - without this, it's not possible to know if the function succeeded.

(I ended up not pursuing this API further and doing something else, but I'm keeping the issue open in case it may be helpful in general)

**Comment by amerkoleci** [comment]
Hi,
Feel free to submit PR.


Thanks
