### ISSUE TITLE
UIAnimation Vector related API can be more simpler

### ISSUE THREAD

**Issue by sdcb** [amerkoleci/Vortice.Windows#325]
This is related to: https://github.com/amerkoleci/Vortice.Windows/issues/324

Not sure it's easy or not, but according to document: https://docs.microsoft.com/en-us/windows/win32/api/uianimation/nf-uianimation-iuianimationmanager2-createanimationvectorvariable

`cDimension` should be the sizeof array `initialValue`, in this case, we should try get array length instead of pass a new parameter.
![image](https://user-images.githubusercontent.com/1317141/177233036-463965c8-19f0-47c1-8dbd-31ea659267b5.png)
Like this:
`IUIAnimationVariable2 CreateAnimationVectorVariable(double[] initialValue);`

And get vector value should have a overload that try return to double[] directly without passing any element, 
![image](https://user-images.githubusercontent.com/1317141/177233212-f2e04885-2d85-42b1-a01b-66c40b139d1e.png)

Like this:
```csharp
double[] GetVectorValue();
```

And some Get/Set method API call should be able to change into properties:
![image](https://user-images.githubusercontent.com/1317141/177233642-60ede29a-228e-42aa-a31e-a5a96d3a3d2b.png)

Like this:
```csharp
double PreviousValue { get; }
double[] PreviousVectorValue { get; }
```

**Comment by sdcb** [comment]
Ok, I figured out it seems the question No.1 can be done by following statement:
```xml
<map param="IUIAnimationManager2::CreateAnimationVectorVariable::cDimension" relation="length(initialValue)" />
```

**Comment by amerkoleci** [comment]
Fixed by https://github.com/amerkoleci/Vortice.Windows/commit/14d7a9ecb6edf7f09d03b3344d330f08373d6a24
