### ISSUE TITLE
ID3D11DeviceContext.Map produces empty byte[]

### ISSUE THREAD

**Issue by CharlesPublic** [amerkoleci/Vortice.Windows#33]
Hey, i'm currently trying to port some code from SharpDX to Vortice.

I'm trying to capture the screen and convert it to a Bitmap or byte[]

When i call the following functions with the same arguments as in SharpDX i only get a blank image or empty byte[]

    ID3D11Device.ImmediateContext.CopyResource, (This can silently fail?)
    ID3D11Device.ID3D11DeviceContext.Map

Can you spot any errors in my code, or things im forgetting, i tryed to port it 1:1 from SharpDx to Vortice and all the objects look the same.

The error happens after i copy the contents from 
MappedSubresource.PData, into a byte[]

Line:
Marshal.Copy(srcPtr, testArr, 0, (int)srcLen);

The same code works when i execute it in my SharpDX test solution.

[CaptureScreenVortice.txt](https://github.com/amerkoleci/Vortice.Windows/files/3759978/CaptureScreenVortice.txt)

The code im trying to port is;
https://github.com/jasonpang/screenshare/blob/master/ScreenShare.Common/ScreenCapture/DxgiOutputDuplicator.cs

Cheers

**Comment by CharlesPublic** [comment]
nvm, after hours of debugging i found my mistake.
You Switched CopyResource( dstResourceRef and srcResourceRef ) !!!
Thats just cruel, when porting from SharpDX.

Anyway thanks for this project, i couldn't even get SharpDX to compile.

i have another question: If i wanna do lots of AcquireNextFrame, can i just reuse the ID3D11DeviceContext every time, or do i have to call .Map(), .Unmap() for every Frame?

**Comment by amerkoleci** [comment]
Dude, I'm following Microsoft API not SharpDX (https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-copyresource) so if it takes first destination then source I follow that API, you have to adapt or follow SharpDX logic.

I will try to improve the Map to have some better logic, maybe using Span stuff.

**Comment by amerkoleci** [comment]
API improvements, and added AsSpan to MappedSubresource so you can access data in the way you want.
