### ISSUE TITLE
nuget package update order issue

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Windows#333]
When updating nuget packages, there is some kind of order required to get them to update, or else they won't update. For example, I can't update Direct2D1 before updating DXGI. Could we have this requirement removed so that I can just go through and update the packages without having to think about the order? Edit: Actually, it seems like if I do DXGI first, then I can just go through each of the packages and update them in the order they are listed then.

Also, this is always reported..

NotFound https://www.myget.org/F/sharpgentools/api/v3/flatcontainer/vortice.dxc/index.json 1093ms

**Comment by amerkoleci** [comment]
Not sure what is causing this issue, I don't have any update nuget issues, but I would suggest to always use the same version in all dependencies.
