### ISSUE TITLE
Vortice.DXGI.FormatHelper.SizeOfInBytes has been incorrectly renamed to BitsPerPixel

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Windows#334]
The function BitsPerPixel should be BytesPerPixel.

**Comment by amerkoleci** [comment]
Mm, I don't this so, its the same from here: https://github.com/microsoft/DirectXTK12/blob/main/Src/LoaderHelpers.h#L27

I'll change documentation of function

**Comment by Gavin-Williams** [comment]
It's an odd change, because how I've been using it is to get the bytesPerPixel to build a data stream...
```
  int bytesPerPixel = Vortice.DXGI.FormatHelper.BitsPerPixel(dxTexture.Description.Format);
  Vortice.DataStream dataStream = new(bytesPerPixel * w * h, true, true);
```
I'm not sure if I ever need the number of bits. I think it's an odd helper method.

**Comment by amerkoleci** [comment]
Well thats correct name, size is expressed in bits and not bytes, for example r32g32b32a32_float is 128bit format, similar like unity3d docs for example
