### ISSUE TITLE
XAudio2 SourceVoice State.SamplesPlayed doesn't update

### ISSUE THREAD

**Issue by jdpurcell** [amerkoleci/Vortice.Windows#34]
I was curious to try your XAudio2 library so I took some of my code that was using SlimDX's XAudio2 and ported it over. I ran into an issue because I have logic to try to keep a certain amount of data buffered in the output device at any given time, so it tries to calculate how many samples are currently buffered by doing something like:

```
long samplesAwaitingPlayback = _totalSamplesSubmitted - (long)_sourceVoice.State.SamplesPlayed;
```

In Vortice.XAudio2 v1.3.0, SamplesPlayed is always 0 so it made my code think the buffer was never emptying and therefore it stopped playing.

**Comment by jdpurcell** [comment]
I can't reproduce this after making a minimal test case in a new project. The same minimal code is failing in my original project so maybe it's different settings or a conflicting reference. I'll let you know if I figure out where the problem is.

**Comment by jdpurcell** [comment]
SamplesPlayed is only returning a value if it's running in 32-bit mode (targeting x86 or AnyCPU with Prefer 32-bit). In 64-bit mode it's always returning 0.

Minimal test case:
```csharp
static void Main(string[] args)
{
	using (var device = new IXAudio2())
	using (var masteringVoice = device.CreateMasteringVoice())
	using (var sourceVoice = device.CreateSourceVoice(new WaveFormat()))
	{
		sourceVoice.Start();
		sourceVoice.SubmitSourceBuffer(new AudioBuffer(new byte[8820]));
		Thread.Sleep(25);
		Console.WriteLine(sourceVoice.State.SamplesPlayed);
		Console.ReadKey(true);
	}
}
```

**Comment by amerkoleci** [comment]
This seams something related to XAudio, there is also XAUDIO2_VOICE_NOSAMPLESPLAYED to be passed to not calculate the sample, maybe you could use XAudio callbacks for this purpose (https://docs.microsoft.com/en-us/windows/win32/api/xaudio2/nf-xaudio2-ixaudio2sourcevoice-getstate)

**Comment by jdpurcell** [comment]
Same issue that was fixed in SharpDX: https://github.com/sharpdx/SharpDX/issues/709
