### ISSUE TITLE
Bug at ID3D11Device.CreateInputLayout().

### ISSUE THREAD

**Issue by haruby511** [amerkoleci/Vortice.Windows#36]
At [ID3D11Device.CreateInputLayout()](https://github.com/amerkoleci/Vortice.Windows/blob/fac349ff6a20ed8bed9d89f2499066c342e22cca/src/Vortice.Direct3D11/ID3D11Device.cs#L150).

It passing size as `blob.BufferPointer`.

Should be
```csharp
return CreateInputLayout(inputElements, inputElements.Length, blob.BufferPointer, blob.BufferSize);
```

**Comment by amerkoleci** [comment]
Nice catch, if you want submit PR otherwise will fix it ASAP

**Comment by haruby511** [comment]
@amerkoleci Unfortunately, I'm a NuGet user and didn't fork the repository. This issue is not emergency because of a overloading which is receiving `byte[]` it works normally. Just inefficient.
