### ISSUE TITLE
Activate assembly signing

### ISSUE THREAD

**Issue by piotrek1668** [amerkoleci/Vortice.Windows#360]
Hello!

For better compatibility with net48 projects that uses assembly signing, it is recommended to enable assembly signing for the Vortice-libraries.

Can I re-enable assembly singing in the file?

In version 2.1.0 of the library the assembly signing was still active, is there a reason why this has been disabled?

https://github.com/amerkoleci/Vortice.Windows/blob/66e8cac2f955bd1eb5585f19fdb4f8a0501d95e2/Directory.Build.props#L19

**Comment by amerkoleci** [comment]
Enabled with this commit: https://github.com/amerkoleci/Vortice.Windows/commit/9092e763393f2604cc93c5a56969b6b0401e0869
