### ISSUE TITLE
Blend State issue

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Windows#363]
OMSetBlendState in Vortice accepts an int for the sample mask, but DirectX accepts a UINT. Following the Direct X documentation for disabling blend and providing 0xFF FF FF FF for the mask produces incorrect results.

Is this an issue with Vortice or have you decided this for some reason?

**Comment by amerkoleci** [comment]
If pass -1 then its the same, can you try please?

**Comment by Gavin-Williams** [comment]
That didn't work either. hmm, it should have I think.

**Comment by amerkoleci** [comment]
This commit improves marshal logic:

https://github.com/amerkoleci/Vortice.Windows/commit/f7a82740a8285865d01a769144f25f6955f96791

Can you test and tell me if it works?
