### ISSUE TITLE
MaxLOD Capped

### ISSUE THREAD

**Issue by spencer-evans-pnt** [amerkoleci/Vortice.Windows#383]
I've noticed that when creating a ID3D11SamplerState, the MaxLOD gets set to 0 instead of the value I passed in the SamplerDescription. I've tested with the projects in the [Vortice.Windows.Samples](https://github.com/amerkoleci/Vortice.Windows.Samples) repo, and have seen the same result. This is preventing me from sampling at different mip-levels in my pixel shader.

To test, clone the Vortice.Windows.Samples repo, run the D3D11 project DrawTexturedCube with a break point [here](https://github.com/amerkoleci/Vortice.Windows.Samples/blob/main/src/Direct3D11/DrawTexturedCube/Program.cs#L63). Inspect the `_textureSampler.Description` and note the MaxLOD value.

You can also test it with this code in a D3D11 project:
`var textureSampler = Device.CreateSamplerState(SamplerDescription.LinearWrap);`

Is anyone experience this? Does anyone know if this is related to my hardware or if it's a bug in the framework?

Thanks in advance, and thank you @amerkoleci for your hard work on this framework!

**Comment by amerkoleci** [comment]
Hi,
Thanks for finding this issue, the next 2.4.1-beta nuget contains fix (https://github.com/amerkoleci/Vortice.Windows/commit/1845cc46a65698cc6b3c620253e760bcda2b2de4)

Cheers

**Comment by spencer-evans-pnt** [comment]
Thank you!
