### ISSUE TITLE
Any plans to add DirectInput bindings?

### ISSUE THREAD

**Issue by limocute** [amerkoleci/Vortice.Windows#39]
Any plans to add DirectInput bindings?I ported 2D games to Vortice.Windows.But it doesn't have a DirectInput binding.
Sorry, English is not my native language.
The above is from Google translation.

**Comment by amerkoleci** [comment]
Hi,
At the moment no, as DirectInput is quite legacy stuff, you can try and port it from SharpDX and maybe submit PR.

Thanks

**Comment by BMarques** [comment]
I'd like to bring this topic back, although DirectInput is quite legacy, it's the only means to deal with joysticks and force feedback such as Steering Wheels.
