### ISSUE TITLE
Sponsor access to Vortice.Windows.Examples?

### ISSUE THREAD

**Issue by sanyokdev** [amerkoleci/Vortice.Windows#396]
Hey, can you invite me to: https://github.com/amerkoleci/Vortice.Windows.Samples
Thanks for the work you do, solid binding!

**Comment by sanyokdev** [comment]
Just got an email for the invite :)
No need for the issue.

**Comment by amerkoleci** [comment]
> Just got an email for the invite :) No need for the issue.

You don't have to become sponsor just to immediatelly cancel sponsorship, I would give you "free" access in that case.
