### ISSUE TITLE
SPIR-V is not generated.

### ISSUE THREAD

**Issue by FaberSanZ** [amerkoleci/Vortice.Windows#41]
Hi,

First of all, thank you very much for the libraries.

I have an error generating SPIR-V   
![Captura](https://user-images.githubusercontent.com/39819646/69886375-aaa8fe00-12af-11ea-9eb3-552fea9a40ef.PNG)
, and downloading the last binary from [dxcompiler.dll](https://dev.azure.com/msft-ShaderConductor/public/_build/results?buildId=149)
works correctly

**Comment by amerkoleci** [comment]
Send PR with latest dxcompiler please, otherwise I will do it asap
