### ISSUE TITLE
ConvolveMatrix D2D effect parameter error.

### ISSUE THREAD

**Issue by Steph55** [amerkoleci/Vortice.Windows#412]
The property KernelUnitLehgth in the ConvolveMatrix D2D effect is not only written incorrectly, but I receive the following message when I try to read it or write to it: 

SharpGen.Runtime.SharpGenException : 'HRESULT: [0x80070057], Module: [Vortice.Direct2D1], ApiCode: [WINCODEC_ERR_INVALIDPARAMETER/InvalidParameter]

**Comment by amerkoleci** [comment]
Fixed by: https://github.com/amerkoleci/Vortice.Windows/commit/224188518e6aa24b8c08d6eeb756f66ea2688835

**Comment by Steph55** [comment]
The orthographic error is fixed, but I still get the same bug when I read or write to this property:

SharpGen.Runtime.SharpGenException : 'HRESULT: [0x80070057], Module: [Vortice.Direct2D1], ApiCode: [WINCODEC_ERR_INVALIDPARAMETER/InvalidParameter]

**Comment by amerkoleci** [comment]
Thats direct2d1 error, not vortice, try to ask on directx discord.

**Comment by Steph55** [comment]
Interesting... I guess this is related to the fact that this attribute is now deprecated in the SVG spec for the feConvolveMatrix filter, so Microsoft seems to be keeping D2D up to date with current trends.
