### ISSUE TITLE
Vortice.Direct2D1.Effects.Vignette throws Exception

### ISSUE THREAD

**Issue by TheBarnyOfBarnim** [amerkoleci/Vortice.Windows#418]
Setting the `Color` property of an `Vortice.Direct2D1.Effects.Vignette` throws an exception because Direct2D expects a `Vector4` instead of a `Vector3`

Example:
```cs
var Effect = new Vortice.Direct2D1.Effects.Vignette(g.DeviceContext);

Effect.SetInput(0, MyTexture, false);

Effect.Color = new System.Numerics.Vector3(Color.R, Color.G, Color.B); //Exception, must be a Vector4

Effect.TransitionSize = 35;
Effect.Strength = 0.75f;
```

**Comment by amerkoleci** [comment]
Can you submit PR? otherwise I'll fix it Monday.

Thanka!

**Comment by TheBarnyOfBarnim** [comment]
Apparently even the official Microsoft Direct2D documentation has errors:

![grafik](https://github.com/amerkoleci/Vortice.Windows/assets/118688494/1442ada2-2d8e-4fb7-9504-83fdd1cc1df3)
_https://learn.microsoft.com/en-us/windows/win32/direct2d/vignette-effect_

![grafik](https://github.com/amerkoleci/Vortice.Windows/assets/118688494/598f3917-1ea0-4c7f-a2dd-8325f78af4e0)
_https://learn.microsoft.com/en-us/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_vignette_prop_
