### ISSUE TITLE
Desktop Duplication Sample

### ISSUE THREAD

**Issue by GTANAdam** [amerkoleci/Vortice.Windows#42]
Greetings, I found some API difficulties coming from SharpDX, would be great to see how this is implemented on Vortice with a sample, thanks in advance.

**Comment by amerkoleci** [comment]
If you have any C++ example port it and I will gladly merge it

**Comment by Velocity-plus** [comment]
I'm not sure if this is what @GTANAdam referred to, but I would love to see how this can be implemented from SharpDX to Vortice.Windows
https://github.com/sharpdx/SharpDX-Samples/blob/master/Desktop/Direct3D11.1/ScreenCapture/Program.cs

**Comment by digitalml** [comment]
Any updates on this? Is the Desktop Duplication API part of Vortice.Windows?  Here is a good c# sample of how it was used in SharpDX

**Comment by sdcb** [comment]
SharpDX desktop duplicate demo here:
```csharp
void Main()
{
	IEnumerable<DataBox> CaptureScreenFrames(int screenId, CancellationToken cancellationToken)
	{
		using var factory = new Dxgi.Factory1();
		using Dxgi.Adapter adapter = factory.GetAdapter1(0);
		using var device = new D3D11.Device(adapter);
		using Dxgi.Output output = adapter.GetOutput(screenId);
		using Dxgi.Output1 output1 = output.QueryInterface<Dxgi.Output1>();
	
		Rectangle bounds = output1.Description.DesktopBounds;
		var textureDesc = new D3D11.Texture2DDescription
		{
			CpuAccessFlags = D3D11.CpuAccessFlags.Read,
			BindFlags = D3D11.BindFlags.None,
			Format = Dxgi.Format.B8G8R8A8_UNorm,
			Width = bounds.Width,
			Height = bounds.Height,
			OptionFlags = D3D11.ResourceOptionFlags.None,
			MipLevels = 1,
			ArraySize = 1,
			SampleDescription = { Count = 1, Quality = 0 },
			Usage = D3D11.ResourceUsage.Staging
		};
	
		using Dxgi.OutputDuplication duplication = output1.DuplicateOutput(device);
		while (!cancellationToken.IsCancellationRequested)
		{
			GrabResult frame = duplication.Grab(20);
			if (frame != null && frame.Resource != null && !cancellationToken.IsCancellationRequested)
			{
				using D3D11.Texture2D currentFrame = new D3D11.Texture2D(device, textureDesc);
	
				using (D3D11.Texture2D rawTexture2d = frame.GetTexture2D())
				{
					device.ImmediateContext.CopyResource(rawTexture2d, currentFrame);
				}
				DataBox dataBox = device.ImmediateContext.MapSubresource(currentFrame, 0, D3D11.MapMode.Read, D3D11.MapFlags.None);
				yield return dataBox;
				duplication.ReleaseFrame();
			}
		}
	}
}

public class GrabResult
{
	public Dxgi.OutputDuplicateFrameInformation FrameInfo { get; }
	public Dxgi.Resource Resource { get; }

	public D3D11.Texture2D GetTexture2D() { return Resource.QueryInterface<D3D11.Texture2D>(); }

	public GrabResult(Dxgi.OutputDuplicateFrameInformation frameInfo, Dxgi.Resource resource)
	{
		FrameInfo = frameInfo;
		Resource = resource;
	}
}

namespace System
{
	public static class OutputDuplicationExtensions
	{
		public static GrabResult Grab(this Dxgi.OutputDuplication duplication, int timeoutInMilliseconds = int.MaxValue)
		{
			Result result = duplication.TryAcquireNextFrame(timeoutInMilliseconds,
				out Dxgi.OutputDuplicateFrameInformation frameInfo,
				out Dxgi.Resource desktopResource);
			if (result.Failure) return null;
			return new GrabResult(frameInfo, desktopResource);
		}
	}
}
```

**Comment by diogotr7** [comment]
I'm also having problems with this. I tried to replicate a *working* snippet that uses SharpDX with Vortice and all i get is a black bitmap. 

@amerkoleci If there's anything obviously wrong with this please let me know. 

[DesktopDuplicators.zip](https://github.com/amerkoleci/Vortice.Windows/files/5386717/DesktopDuplicators.zip)

Of course once itworks I can submit a pull request with the sample code for other people to use.

**Comment by DaniilSokolyuk** [comment]
@diogotr7 swap arguments here
`device.ImmediateContext.CopyResource(tempTexture, currentFrame);`

**Comment by diogotr7** [comment]
Thanks @DaniilSokolyuk , thankfully i ended up figuring this out and forgot about this issue. The arguments being in a different order than in SharpDX is confusing.

I've published this sample [here](https://github.com/diogotr7/DesktopDuplicationSamples) in case it is useful to someone else.

**Comment by amerkoleci** [comment]
Why would SharpDX change order than native is confuse not the vortice ones.

Anyway glad you sorted out, closing.
