### ISSUE TITLE
Need Direct3D 9 till these days.

### ISSUE THREAD

**Issue by haruby511** [amerkoleci/Vortice.Windows#43]
The Vortice seems has not any plan for D3D9. Maybe because it is very old.
However, in WPF(Windows Presentation Framework), the D3D9 is the only way of low-level GPU acceleration rendering.

The [D3DImage](https://docs.microsoft.com/en-us/dotnet/api/system.windows.interop.d3dimage.setbackbuffer?view=netframework-4.8#System_Windows_Interop_D3DImage_SetBackBuffer_System_Windows_Interop_D3DResourceType_System_IntPtr_) support D3D in WPF and it only accept D3D9 texture for its backbuffer.

Therefore, we need to create a shared D3D9 texture for D3D11, D3D12 or any other D3D to do actual rendering.
Of course, we can do it in Win32 or C++/CLI but we have to use x86/x64 or [DLLImport] instead of Any CPU.

In SharpDX, this is not a problem because it didn't drop the D3D9 till been retired.

**Comment by amerkoleci** [comment]
Feel free to submit PR, not in the plan in near future

**Comment by amerkoleci** [comment]
Initial Direct3D9 support just landed (https://github.com/amerkoleci/Vortice.Windows/commit/f419c92f0c6307325a29e1a4a161d1563edf19fe)

**Comment by haruby511** [comment]
@amerkoleci Nice job. I'll try it soon.

**Comment by haruby511** [comment]
@amerkoleci Missing NuGet package.

**Comment by amerkoleci** [comment]
@haruby511 You need nightly builts, still not ready for nuget, please take look on how to that in README.

Basically you need to add the line bellow in your nuget.config file:

<add key="myget vortice_windows" value="https://ci.appveyor.com/nuget/vortice-windows" />

**Comment by amerkoleci** [comment]
Just released nuget package as well, closing
