### ISSUE TITLE
Compile error with Vortice.Direct3D9, etc.

### ISSUE THREAD

**Issue by tictac1234** [amerkoleci/Vortice.Windows#433]
Hello.

I was using SharpDX and I am thinking of moving to Vortice.

However, I am unable to compile the following project...

-  Vortice.Direct3D9
- Vortice.Wpf
- Vortice.UIAnimation
- Vortice.Dxc

`error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: SharpGen.Runtime.COM;Vortice.Mathematics;SharpGen.Runtime.COM;Vortice.Mathematics.`

Also, for some reason, I can't open Nuget Manager from Vortice.Direct3D9 project.

I want to custom build and use Vortice.Direct3D9, so it would be very helpful if you could address this issue.

Thank you.

**Comment by amerkoleci** [comment]
Hi,
I don't have any issues building non of the projects you said, in case please use nuget releases or just simple add support for central packages support.

https://github.com/amerkoleci/Vortice.Windows/blob/main/Directory.Build.props#L24C6-L24C36
https://github.com/amerkoleci/Vortice.Windows/blob/main/Directory.Packages.props

Docs here:
https://learn.microsoft.com/it-it/nuget/consume-packages/central-package-management

**Comment by tictac1234** [comment]
As shown below, all builds from the command prompt were successful.

`dotnet restore`
`dotnet build`

However, Ppening Vortice.Windows.sln, and try to build from Visual Studio, it fails with the error mentioned earlier.

For now, I will build from the command prompt.
Thanks you.
