### ISSUE TITLE
Vortice.Direct3D12.CPUDescriptorHandle.Offset(int, int) not giving correct address.

### ISSUE THREAD

**Issue by MarcioAB** [amerkoleci/Vortice.Windows#436]
It seems Vortice.Direct3D12.CPUDescriptorHandle.**Offset**(int, int) is not giving correct address.

Check using 3 different ways to get this address:

```
var handle = rtvDescriptorHeap.GetCPUDescriptorHandleForHeapStart();

for (int i = 0; i < 10; i++) {
	handles1[i] = handle + i * rtvDescriptorSize; // OK
	handles2[i] = new CpuDescriptorHandle(handle, i, rtvDescriptorSize); // OK
	handles3[i] = handle.Offset(i, rtvDescriptorSize); // Not OK
}
```

handles1 and handles2 have correct address but not handles3.

**Comment by amerkoleci** [comment]
Found the issue, will push fix tomorrow. 

Thanks!

**Comment by amerkoleci** [comment]
Can you try with https://github.com/amerkoleci/Vortice.Windows/commit/f49856e33e83d2a9470d38c674a4fa0293a70100 and tell me if it works?

**Comment by MarcioAB** [comment]
Sorry, I misunderstood the Offset function.
I did not realize that it does not create a new handle but merely offsets the pointer of the current handle.
I now realize the static CpuDescriptorHandle.InitOffsetted is the one to do that, besides the others I used to check.
They are all working fine for me.
