### ISSUE TITLE
Vortice.Wpf does not show anything

### ISSUE THREAD

**Issue by MariusMichelPrimes** [amerkoleci/Vortice.Windows#446]
I am searching for a good replacement for an old SharpDX Wpf control and tried the Vortice.Wpf lib. But it does not show anything.
I think you forgot to create the ColorTextureView. If I add ColorTextureView = _device.CreateRenderTargetView(ColorTexture); in the CreateAndBindTargets function of the DrawingSurface, everthing seems to be fine.

**Comment by amerkoleci** [comment]
Thanks for spotting this, fixed by https://github.com/amerkoleci/Vortice.Windows/commit/799cd122b07acab8bced505fd49517426a41fdbc

version 3.5.5-beta is coming
