### ISSUE TITLE
IDxcCompilerArgs binding is wrong

### ISSUE THREAD

**Issue by DeadMG** [amerkoleci/Vortice.Windows#447]
To reproduce, use IDxcUtils::BuildArguments. Then use the Arguments property on IDxcCompilerArgs. You will get out garbage.

It seems like the binder is treating the result as a string, when it is an array of strings.

**Comment by amerkoleci** [comment]
Can you share a repro case please?

**Comment by DeadMG** [comment]
Can do this evening

**Comment by DeadMG** [comment]
```
namespace VorticeRepro
{
    internal class Program
    {
        static void Main()
        {
            using (var utils = Vortice.Dxc.Dxc.CreateDxcUtils())
            using (var args = utils.BuildArguments("test.hlsl", "test1", "lib_6_3", ["test2"], []))
            {
                Console.WriteLine(args.Arguments);
            }
        }
    }
}
```

This simple sample should produce some command line arguments, but instead, "??O" was printed. Looking at Arguments in the original C++ API, it is an array of strings rather than a single string, which is probably the issue.

**Comment by amerkoleci** [comment]
Fixed by https://github.com/amerkoleci/Vortice.Windows/commit/420b46aafa8b8c9e38ca1a115e104aa3125c5dba

Thanks for repro case, version `3.5.6 beta` is comming
