### ISSUE TITLE
MFCreateVirtualCamera

### ISSUE THREAD

**Issue by andreysaf** [amerkoleci/Vortice.Windows#451]
First of all, thank you for all your hard work. I was wondering if it is within the scope of your project to add [MFCreateVirtualCamera](https://learn.microsoft.com/en-us/windows/win32/api/mfvirtualcamera/nf-mfvirtualcamera-mfcreatevirtualcamera)?

**Comment by amerkoleci** [comment]
Hi,
Feel free to submit PR.

Thanks!

**Comment by andreysaf** [comment]
Thank you so much!
