### ISSUE TITLE
Add support for D3D12GetInterface

### ISSUE THREAD

**Issue by DeadMG** [amerkoleci/Vortice.Windows#455]
There's a generated interface for ID3D12SDKConfiguration1, but according to https://web.archive.org/web/20220927101853/https://microsoft.github.io/DirectX-Specs/d3d/IndependentDevices.html, it should be created with https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-d3d12getinterface, and this seems to have a private API but not a public one.

**Comment by amerkoleci** [comment]
Hi,
Thanks for bringing this out, version `3.5.13-beta` with https://github.com/amerkoleci/Vortice.Windows/commit/74ece688c0b528d9aa592a4fc25f8d69d94e184a

Thanks!
