### ISSUE TITLE
Can't run WinUI with Vortice. 3.6.2 and Dot Net 8 in release mode

### ISSUE THREAD

**Issue by TomAtWork** [amerkoleci/Vortice.Windows#459]
Hi, 
after migrating to DotNet 8 I can't run my application in release mode - in debug mode it works. 
I tracked this down to the call `var comObject = ComObject(swapChainPanel)`.

To reproduce this issue you can 
- create a Blank WinUI App (Packaged) with VS2022 17.11.5, 
- add an Microsoft.UI.Controls.SwapChainPanel and
- install SharpGen.Runtime 2.2.0-beta. 

The call
`var comObject = new SharpGen.Runtime.ComObject(SwapChainCanvas); `
does not return in release mode.

Does anyone knows a workaround ? 
Thanks in advance
Tom

**Comment by TomAtWork** [comment]
Hi,
I have changed the initialization to

```
...
Guid guid = typeof(Vortice.WinUI.ISwapChainPanelNative).GUID;
Result result = ((IWinRTObject)this).NativeObject.TryAs(guid, out var swapChainPanelNativeHandle);
result.CheckError();
...
```
like in the sample found in [Vortice.Windows.Samples](https://github.com/amerkoleci/Vortice.Windows.Samples) and this works now ! 
Don't know why the call to `var comObject = ComObject(swapChainPanel)` didn't worked.

I think this issue can be closed!

Thanks,
Tom

**Comment by amerkoleci** [comment]
> Hi, I have changed the initialization to
> 
> ```
> ...
> Guid guid = typeof(Vortice.WinUI.ISwapChainPanelNative).GUID;
> Result result = ((IWinRTObject)this).NativeObject.TryAs(guid, out var swapChainPanelNativeHandle);
> result.CheckError();
> ...
> ```
> 
> like in the sample found in [Vortice.Windows.Samples](https://github.com/amerkoleci/Vortice.Windows.Samples) and this works now ! Don't know why the call to `var comObject = ComObject(swapChainPanel)` didn't worked.
> 
> I think this issue can be closed!
> 
> Thanks, Tom

You need <BuiltInComInteropSupport>true</BuiltInComInteropSupport> in your csproj to make it work, can you try please?

**Comment by TomAtWork** [comment]
Yes, that worked !
Thank you Armer. 

Is there any advantage using the ComObject compared to the code from the previous message ?
