### ISSUE TITLE
DXGIDebugInterface1 in different dll.

### ISSUE THREAD

**Issue by BMarques** [amerkoleci/Vortice.Windows#46]
Hello,
While trying to use the DXGI.DXGIDebugInterface1, it was complaining it wasn't finding that method in dxgidebug.dll. I fixed it by changing the dxgidebug.dll to dxgi.dll. in the following mapping

`<map function="DXGIGetDebugInterface.*" dll='"dxgi.dll"' group="Vortice.DXGI.DXGI" hresult="true" check="false" />
<map param="DXGIGetDebugInterface.*?::ppDebug" attribute="out" />`

**Comment by amerkoleci** [comment]
Fixed, thanks!
