### ISSUE TITLE
Add no spaces requirement to the build instructions

### ISSUE THREAD

**Issue by Jure-BB** [amerkoleci/Vortice.Windows#48]
I was having issues building this project because I had spaces in the project path. This seems to be caused by SharpGenTools/CastXML module. 

It would be nice, if no spaces in project path requirement was added to the build instructions in the readme, as this is not standard requirement for C# projects.

**Comment by amerkoleci** [comment]
Added info in README.md

**Comment by riQQ** [comment]
This was probably fixed by #193.

Corresponding issue: https://github.com/SharpGenTools/SharpGenTools/issues/86.
