### ISSUE TITLE
[Question] Is it possible to use this to capture a Window client area for a screenshot?

### ISSUE THREAD

**Issue by pjmagee** [amerkoleci/Vortice.Windows#49]
I have a .NET core 3.1 application and i've been using native calls to GDI resources, however on some devices the hardware does not support BitBlt (My laptop doesn't work, but my Desktop does). The resulting bitmap is just black. It seems like the best way to approach this is a hook or some form of direct x capabilities so that it can work across any hardware its running on. I'm not familiar with this and have been doing ok with simple BitBlt for screen capture of a window which i am performing some OCR on. Would it be possible to use this library to capture a frame?

**Comment by amerkoleci** [comment]
Not sure how to answer this, if you have an example of cpp code I can help out
