### ISSUE TITLE
XInput support

### ISSUE THREAD

**Issue by amerkoleci** [amerkoleci/Vortice.Windows#5]
Add XInput bindings support.

**Comment by amerkoleci** [comment]
@nathan-alden Initial XInput support has just landed

**Comment by nathan-alden** [comment]
Where can I get these NuGet packages? I added a package source to your MyGet but no packages show up:
```
<add key="myget-vortice" value="https://www.myget.org/F/vortice/api/v3/index.json" />
```

**Comment by nathan-alden** [comment]
Never mind; found them! They are prerelease packages.
