### ISSUE TITLE
Error messages lacking details

### ISSUE THREAD

**Issue by YaakovDavis** [amerkoleci/Vortice.Windows#50]
The error messages just say "the parameter is incorrect", and don't contain any useful information.
How to fix this?

**Comment by amerkoleci** [comment]
Cmon, share some code or callstack so i can help out, this doesn't mean nothing otherwise

**Comment by YaakovDavis** [comment]
Here's one callstack as an example, but I get the same error in many other scenarios:

```
HRESULT: [0x80070057], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The parameter is incorrect.
   at SharpGen.Runtime.Result.CheckError()
   at Vortice.Direct3D11.ID3D11Device.CreateShaderResourceView(ID3D11Resource resourceRef, Nullable`1 descRef)
   at vorticeCore.Program.work() in C:\Users\Yaakov\Desktop\Game1\vorticeCore\Program.cs:line 161
   at vorticeCore.Program.Main() in C:\Users\Yaakov\Desktop\Game1\vorticeCore\Program.cs:line 71
```

To be clear, I know how to fix the above error. The problem is that I get many similar errors, which don't provide any additional info. I have to dig manually, which slows me down.

**Comment by amerkoleci** [comment]
You should act as native code, its the same even on native dx11 code, just enable the debug layer

**Comment by YaakovDavis** [comment]
Enabling the debug layer didn't yield any additional info, but perhaps DX itself doesn't provide any such info.
