### ISSUE TITLE
[DXC] Mesh shaders Support 

### ISSUE THREAD

**Issue by Pursche** [amerkoleci/Vortice.Windows#51]
I would like to request support for the brand new DirectX Mesh Shaders that went into dev preview in October:

https://devblogs.microsoft.com/directx/dev-preview-of-new-directx-12-features/

This introduces the new shader stages "ms_6_5" and "as_6_5", so the bindings would have to get updated with new DxcShaderStages I guess?

I just started using Vortice.DXC after having used dxc.exe through a spawned commandline process, and I must say that it's exactly what I've been wishing for! I am making a game engine in C++, but I have a C# Cooker application to precompile shaders, convert models/textures etc, and now I can finally get rid of the ugly dxc.exe bridge I made. Thank you! :)

**Comment by amerkoleci** [comment]
Of course yes, once the Windows 10 SDK 19041 gets released.

**Comment by amerkoleci** [comment]
Mesh shaders just landed, closing now

**Comment by BitCrusader** [comment]
As of August 2022, DxcShaderStage still doesn't seem to contain an entry for either "Mesh" or "Amplification". What's the status on getting those added?

**Comment by amerkoleci** [comment]
Just a PR away :)

**Comment by amerkoleci** [comment]
Will add it tomorrow

**Comment by BitCrusader** [comment]
Looks like the two new stages are also missing from GraphicsPipelineStateDescription

**Comment by amerkoleci** [comment]
Take look here  https://github.com/amerkoleci/Vortice.Windows/blob/main/src/samples/HelloDirect3D12/PipelineStateStream.cs#L12,  just add the mesh and amplification stage and job done
