### ISSUE TITLE
CD3D11 Helper Structures

### ISSUE THREAD

**Issue by BMarques** [amerkoleci/Vortice.Windows#53]
Hello,
I'm reimplemeting the UWP DirectX 11 App that comes with Visual Studio, and I came across these helper structures. Is it implemented in some way in Vortice? 
I think it would be a good idea, to make some struct initializations easier. 

I can try to submit a PR, but I still don't quite get how to work with Vortice and SharpGen :).

**Comment by amerkoleci** [comment]
Hi,
For helpers you dont need to pass throught CD3D11 logic, you can extend descriptors like being done in native side, feel free to submit PR or tell me which structures you need.

Thanks

**Comment by BMarques** [comment]
My idea was to add the same logic of those helpers to the constructors for the respective vortice d3d11 structs. Is that what you meant with extend descriptors?

**Comment by amerkoleci** [comment]
Yes, without touching the SharpGen side

**Comment by BMarques** [comment]
I'll give it a try

**Comment by amerkoleci** [comment]
I'm doing it, will push changes soon.

**Comment by BMarques** [comment]
Thanks. When do you think you'll release version 1.6.0?

**Comment by amerkoleci** [comment]
Its depends, you can use beta packages that I'm now pushing on nuget as well (https://www.nuget.org/packages/Vortice.Direct3D11/1.6.1-beta-g6ca1898ae1)

**Comment by BMarques** [comment]
Thanks, I'll give it a try later today.
