### ISSUE TITLE
ClearRenderTargetView Color improvement

### ISSUE THREAD

**Issue by BMarques** [amerkoleci/Vortice.Windows#54]
Hello,
According to this documentation, https://github.com/microsoft/DirectXTK/wiki/Using-DeviceResources, the DirectXMath colors are based on the .NET color constants.
With this in mind, I think it make sense that ClearRenderTargetView actually takes a System.Drawing.Color as input, then convert the Color to a Color4 using a specific Color4 constructor.

What do you think? It makes it more seamless and intuitive.

**Comment by amerkoleci** [comment]
Nice idea, indeed I have done the integration here (https://github.com/amerkoleci/Vortice.Windows/commit/01e9049c4cf9e83fd9e8571ab117dd1a13fe46ad)
