### ISSUE TITLE
COM memory behavior for IDXGIFactory1.EnumAdapters1

### ISSUE THREAD

**Issue by acaly** [amerkoleci/Vortice.Windows#58]
Hi,

Could you please explain whether or how I should release adapters returned by ```IDXGIFactory1.EnumAdapters1```? From the source code I see it directly calls the native ```EnumAdapters1``` function, which I think automatically ```AddRef``` for each returned pointer. I think the caller should Release all elements returned by this method?

I noticed that in src/samples/Vortice.SampleFramework/D3D12GraphicsDevice.cs, this is not done.

Thanks!

**Comment by acaly** [comment]
Similar for ```IDXGIAdapter.EnumOutputs```.

**Comment by acaly** [comment]
I have tested this myself. I did not figure out how to use the memory leak reporting system in CppObject, so I manually checked memory heap in VS.

I noticed that SharpDX originally uses the similar method (of returning an array of COM objects). According to the discussion in https://github.com/sharpdx/SharpDX/pull/102, "You can request adapters/outputs as many times and not release them, It will not change the memory of the application. " However, this claim, although from the member of SharpDX library, is unfortunately not the truth. Every COM function returning a COM pointer will ```AddRef``` it automatically, leaving the ```Release``` work to caller. I have tested both SharpDX (4.2.0.0) and this library. Requesting an ```Adapter```'s outputs repeatedly will keep increasing memory usage. GC is constantly running during this and managed heap does not increase significantly as expected, while unmanaged heap can increase by several GBs, indicating unmanaged COM objects are not released properly. Calling ```Dispose``` (which ```Release``` the COM object) after each request solves the memory leak.

So the conclusion is, if these methods are expected to be called for only a few times during the lifetime of application, leaving it undisposed should be fine. In order to strictly ensure memory safety, however, one should call ```Dispose``` on each element returned in the array.

Using a method as in this library is actually better than the property in SharpDX, provided that there is memory allocation. Disposing a returned array is totally acceptable, but disposing something in a property is wired.

This test resolved my question. Please close this if you believe there is no remaining issues.

**Comment by amerkoleci** [comment]
This was handled in this commit: https://github.com/amerkoleci/Vortice.Windows/commit/d2fbca648ec24974a1a4dd37d003a3aee3c60397

Feel free to report any other memory usage.

**Comment by acaly** [comment]
Thank you for the work! I am looking forward to a stable 1.6.0.
