### ISSUE TITLE
Where is the Vortice.XAudio2 NuGet package?

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#6]
I cannot find the `Vortice.XAudio2` NuGet package in your MyGet feed. I did find a package called `Vortice.Audio` but it doesn't look like that's the right one.

**Comment by nathan-alden** [comment]
According to the latest build results, it does not appear that `Vortice.XAudio2` is being published. Probably just an oversight.

https://ci.appveyor.com/project/amerkoleci/vortice-windows

**Comment by amerkoleci** [comment]
XAudio is wip and not ready to use atm, will fix it and publish them

**Comment by nathan-alden** [comment]
Heya, @amerkoleci. I'm curious where this is landing on your roadmap. It's the only thing holding me up from using Vortice in my engine.

**Comment by amerkoleci** [comment]
Hi,
Unfortunatelly I've being busy in other areas (Direct3D12 and Direct2D1), will implement it ASAP.

**Comment by amerkoleci** [comment]
XAudio2 support has landed, please give a try

**Comment by nathan-alden** [comment]
@amerkoleci Did you upload this to NuGet? I can't find it on either nuget.org or myget.org.

**Comment by amerkoleci** [comment]
You need to add appveyor feed, take look at Readme file.
     <add key="myget vortice_windows" value="https://ci.appveyor.com/nuget/vortice-windows" />

**Comment by nathan-alden** [comment]
Ah, I hadn't seen that. Looks like I can get rid of the [presumably old?] MyGet feed URL.

**Comment by amerkoleci** [comment]
Yep
