### ISSUE TITLE
Incorrectly disposing immediate context when creating device

### ISSUE THREAD

**Issue by acaly** [amerkoleci/Vortice.Windows#60]
The device context is disposed by constructor, which causes the immediate context property to be null. I believe this is not the expected behavior. 

https://github.com/amerkoleci/Vortice.Windows/blob/d2fbca648ec24974a1a4dd37d003a3aee3c60397/src/Vortice.Direct3D11/D3D11.cs#L26

**Comment by amerkoleci** [comment]
Do you have null reference here?

**Comment by acaly** [comment]
Using this method, the device is fine, but if I want to get the immediate context later from the device, I get an COM object with null pointer inside. I think either the device should have a valid context object after creation, or create another one when requested (by calling ```ID3D11Device::GetImmediateContext```).

**Comment by acaly** [comment]
Some not really related thoughts. I have to say the memory management of COM objects does not get along well with C# GC, and this type of ```ComObject``` architecture has some limitation. The C++ COM interface, although being complicated, has a rather clear rule of when one should ```AddRef```/```Release``` an object, and everyone can have valid pointers and be happy if the rule is properly followed. This ```ComObject``` does not allow copying (probably except for using ```QueryInterface```?), and thus when someone disposes the object from his/her side, all references to the same object become invalid. There is always an implicit owner of the object that should dispose it, but it's never clear when you become the owner, nor is it clear when the owner will suddenly dispose it.

**Comment by acaly** [comment]
I just noticed that this issue was related to https://github.com/amerkoleci/Vortice.Windows/issues/30. However, as the device should dispose the immediate context when itself is disposed, I don't see why it causes a memory leak if the context is not disposed in this method.

I actually doubt the leak is caused by https://github.com/amerkoleci/Vortice.Windows/blob/cae261c46564ca66c4cd67ac8877ed2633bbc959/src/Vortice.Direct3D11/D3D11.cs#L64
I know this is corresponding to
https://github.com/amerkoleci/Vortice.Windows/blob/d2fbca648ec24974a1a4dd37d003a3aee3c60397/src/Vortice.Direct3D11/ID3D11DeviceChild.cs#L68

Because some code is generated, it is quite difficult to dig into the original problem in #30 myself. I am not sure how the ```Device__``` field of ```ID3D11DeviceChild``` is initialized, but maybe one should releasing the old reference when replacing with the new one. This is the COM rule.

Still, adding reference count manually is dangerous, as I think the rule of addref/releasing for ComObject is **one ComObject instance corresponds to one reference count**. This is totally different from the COM rule. The AddRef call mentioned above is similar to the COM rule, but could lead to problem for ComObject, since each ComObject only release once in its dispose method. The point of adding an additional reference in device child interface I believe is to keep the device alive even after the user disposes the device. However, even if you have a ComObject with one additional reference count to prevent the unmanaged object to be collected, the native pointer is zeroed anyway whenever someone disposes it
https://github.com/amerkoleci/Vortice.Windows/blob/d2fbca648ec24974a1a4dd37d003a3aee3c60397/src/Vortice.Runtime.COM/ComObject.cs#L217
So you have no way to access the unmanaged object from a null pointer after this, and the remaining reference count in the unmanaged object can no longer be cleared, leading to potential memory leak. According to manual for ```Marshal.AddRef``` in MSDN, this kind of manual reference counting control is needed mainly for marshalling.

**Comment by acaly** [comment]
Sorry for posting again. I looked at the decompiled source/IL using ILSpy. What I found is:
1. Currently there is no memory leak regarding to device or immediate context, or memory access error (except for the mentioned null context).
2. To solve the null context problem, removing the ```Dispose``` call in the mentioned ```D3D11CreateDevice``` method should leads to no memory leak (I still don't understand what caused the the problem in #30). Because the ```Device__``` is null at the beginning, there is also no need to release it before setting the reference. 

Actually I don't think it's necessary to manually set ```Device__```. The ```Device``` property should handle this properly, as in all other device child classes. If this code is removed, the special handling of immediate context when device itself is disposed is also unnecessary, and in the device child class the ```Dispose``` method can also use (the more aggressive) ```Dispose``` instead of ```Release``` on ```Device__```.

**Comment by amerkoleci** [comment]
Do you mind submitting PR? You seams understood correctly the issue

**Comment by amerkoleci** [comment]
Just pushed fix for this one: https://github.com/amerkoleci/Vortice.Windows/commit/6de281baeae3d51b8adccddfa808948664c3e0a5

Can you grab nuget package please?

**Comment by acaly** [comment]
Thanks for fixing this. I will try the latest version.

I think all problems mentioned here are solved. I think I should keep the PR open because it contains fixes for two other problems not mentioned here (please see the 2 examples in the PR comment), although both are less critical.
