### ISSUE TITLE
RaytracingInstanceDescription

### ISSUE THREAD

**Issue by Jorgemagic** [amerkoleci/Vortice.Windows#63]
Hi Amer,
    I have an issue with RaytracingInstanceDescription struct in Vortice.Direct3D12.  The size of this struct in C++ API is 64 ( Ej. sizeof(D3D12_RAYTRACING_INSTANCE_DESC) ) however in Vortice C# API is 48 (Unsafe.SizeOf< RaytracingInstanceDescription >()), and this doesn't work in my DXR sample. I think that you must specify the explicit offset and size of this struct.

I fixed it in my code creating my FixedRaytracingInstanceDescription struct with the following code:
```
 [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct FixedRaytracingInstanceDescription
    {
        [FieldOffset(0)]
        public Matrix3x4 Transform;
        [FieldOffset(48)]
        public int InstanceID;
        [FieldOffset(51)]
        public byte InstanceMask;
        [FieldOffset(52)]
        public int InstanceContributionToHitGroupIndex;
        [FieldOffset(55)]
        public byte Flags;
        [FieldOffset(56)]
        public long AccelerationStructure;
    }
```
And it work fine. What do you think?

**Comment by amerkoleci** [comment]
Nice catch, just fixed with your suggestion and added documentation to the structure.

https://github.com/amerkoleci/Vortice.Windows/commit/38f134d4863c3a74b8826a514d047b1de1ec6809
