### ISSUE TITLE
[D3D11] API design for DeviceContext.Map with mip and array slice parameters

### ISSUE THREAD

**Issue by acaly** [amerkoleci/Vortice.Windows#64]
```C#
public MappedSubresource Map(ID3D11Resource resource, int mipSlice, int arraySlice, MapMode mode, MapFlags flags, out int mipSize)
```
This seems to be an overload designed for textures. I think there are 2 places that can be made better:
1. It should throw NotSupportedException or InvalidOperationException instead of the current NotImplementedException for buffers.
2. There is no corresponding unmap method that accepts the same set of parameters. Users still have to manually calculate subresource index, making it less convenience.

**Comment by amerkoleci** [comment]
What i would like to add is the IDisposable pattern and when disposed call Unmap

**Comment by acaly** [comment]
IDisposable pattern is a good choice from the user's point of view. The problem is only how far you want to be away from the original DirectX API in general. Maybe there are too much to improve to make the whole DirectX API in C# style.

**Comment by acaly** [comment]
Note that even Bitmap.LockBits is not using IDisposable.
