### ISSUE TITLE
Mathematics Viewport

### ISSUE THREAD

**Issue by BMarques** [amerkoleci/Vortice.Windows#66]
Hello,
Should the Viewport struct be part of Mathematics namespace, or Direct3D11 ? I'm asking because it's originally from the D3D11 headers, since it's a "D3D11_VIEWPORT"

I know that there's also a D3D12_VIEWPORT ... so maybe it should actually be just part of the DirectX.Direct3D namespace?

I also noticed that it expects a RectangleF, also from the Mathematics library, but on other parts of the vortice library, you've been changing to the System.Drawing namespace.

**Comment by amerkoleci** [comment]
I'm moving away from system drawing and have all parts in vortice mathematics, Point, PointF, Size, SizeF, Rectangle, Rectangle and Viewport is where it belongs, shared code and I will use same types in https://github.com/amerkoleci/Vortice.Vulkan
