### ISSUE TITLE
Add object tracker similar to SharpDX for memory leak debugging

### ISSUE THREAD

**Issue by holance** [amerkoleci/Vortice.Windows#67]
SharpDX Diagnoistic has the object track, which helps to debug memory leaks.
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/Diagnostics/ObjectTracker.cs

If Vortice can add similar debugging feature, it would be really helpful.

**Comment by amerkoleci** [comment]
This is part of SharpGen.Runtime thus part of vortice.

https://github.com/SharpGenTools/SharpGenTools/blob/23a17e7386d608ee7d03bd0ecc77a0bc2b38b894/SharpGen.Runtime/Diagnostics/ObjectTracker.cs
