### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by zcstkhk** [amerkoleci/Vortice.Windows#69]
Is it possile that add MSDN Doc into the Vortice? SharpDx has accomplished part of them, but i don't follow how that works.

**Comment by Axiverse** [comment]
@amerkoleci @andrew-boyarshin. What is the status of the Microsoft Docs Provider for SharpGenTools? Does that work?

**Comment by Axiverse** [comment]
If it needs work or isn't complete, I'm going to write a scraper for directml related docs.

**Comment by andrew-boyarshin** [comment]
@Axiverse it worked fine, but it often hit the rate limit of GitHub search APIs and it was absolutely unreliable to be run as part of the build. I decided to scrape running it during the build. Instead, some external documentation format should be used (like the ExternalDocs one), but I didn't have the time to adapt the documentation provider.

**Comment by Axiverse** [comment]
I'm doing a manual update process for DirectML from that package. The fields are kinda dirty (though I suspect DirectML is one of the cleaner ones as it's newer). I think the fields don't change that much, and it'd be a chore to have to reprocess everything every build, and it's slowing down with docs already. I'm optimistically generating everything that starts with `DML`_ or `IDML_`. Just run once per update of the docs - (basically the [Microsoft.Windows.CsWin32/Docs.cs](https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32) package.)

See #268
