### ISSUE TITLE
GENERIC_READ and GENERIC_WRITE constants not implemented

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#7]
I am attempting to call `IWICImagingFactory2.CreateDecoderFromFilename`, whose third parameter is `int dwDesiredAccess`. According to MSDN, this value can be set to `GENERIC_READ` and `GENERIC_WRITE`, but I am unable to find those constants defined in Vortice.Windows except as private constants in `IWICStream`. I believe SharpDX implemented this method using a [`NativeFileAccess` enum](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/IO/NativeFileAccess.cs).

**Comment by nathan-alden** [comment]
I added my own version of `NativeFileAccess` to my project:
```
[Flags]
public enum NativeFileAccess : uint
{
    GenericRead = 0x80000000u,
    GenericWrite = 0x40000000u
}
```
However, I get an overflow error during compilation since the compiler is trying to protect me from automatically converting a `uint` to an `int`. I am using the following syntax to override the error: `unchecked((int)NativeFileAccess.GenericRead)`.

Realistically the method signature should probably be changed to `uint` if possible, or even better, to an enum.

**Comment by amerkoleci** [comment]
This one maps to System.IO.FileAccess and I handle the native conversion, fixed now.
