### ISSUE TITLE
Allow only setting UnorderedAccessViews for OutputMerger

### ISSUE THREAD

**Issue by feliwir** [amerkoleci/Vortice.Windows#70]
With **OMSetRenderTargetsAndUnorderedAccessViews** it's possible to set num of rtvs to **D3D11_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL**. Currently this is not possible with Vortice.Windows

**Comment by amerkoleci** [comment]
Do you have other issues?

**Comment by feliwir** [comment]
I didn’t port of everything so far of Veldrid, but i’ll let you know if i hit another blocker

**Comment by amerkoleci** [comment]
Just pushed a fix for this one as well, try to get latest beta packages and see if it works well.
