### ISSUE TITLE
Define debug GUIDs

### ISSUE THREAD

**Issue by feliwir** [amerkoleci/Vortice.Windows#71]
It would be great if the debug guids required for **ReportLiveObjects** could be wrapped somewhere. See: https://docs.microsoft.com/de-de/windows/win32/direct3ddxgi/dxgi-debug-id

I saw that you also use them in alimer and define them manually there:
https://github.com/amerkoleci/alimer/blob/f3eaf2ca6bf9870a317bd3f8bf0e860b29737334/third_party/vgpu/src/vgpu_d3d_common.h#L51

I think it would be convenient if those GUIDs were somehow predefined in Vortice

**Comment by amerkoleci** [comment]
They are indeed wrapped, under Vortice.DXGI dxgi static class

**Comment by feliwir** [comment]
Ah yes, sorry. Didn't find it before :)
