### ISSUE TITLE
Implement the Controller class for XInput

### ISSUE THREAD

**Issue by nathan-alden** [amerkoleci/Vortice.Windows#8]
SharpDX has a controller class: https://github.com/sharpdx/SharpDX/blob/1f89381bc08f2d8cf8d294c6c5fce8dc85a849a1/Source/SharpDX.XInput/Controller.cs

It would be useful to implement this concept in Vortice.XInput.

**Comment by amerkoleci** [comment]
I prefer stay more to XInput api, just call XInput GetState, SetVibration etc
