### ISSUE TITLE
BUG: Cannot pass null to IDXGIDevice.CreateSurface()

### ISSUE THREAD

**Issue by Redninja106** [amerkoleci/Vortice.Windows#83]
I am trying to create a DXGI surface which shares its data with a Direct3D9 surface:

`this.IDXGIDevice.CreateSurface(default, 1, (Vortice.DXGI.Usage)0, new SharedResource() { Handle = d3d9Surface.NativePointer });`

but it throws this error: 

`DXGI ERROR: IDXGIDevice::CreateSurface: If pSharedResource is non-null (meaning open a shared resource), then NumSurfaces must be one, Usage must be zero, and pDesc must be NULL [ MISCELLANEOUS ERROR #63: ]`

Since the `descRef` parameter is a struct, there is no way to pass NULL, and it is impossible to create a shared surface.

**Comment by amerkoleci** [comment]
Thanks for bringing this up, should be fixed in latest beta.

Please try with latest 1.7.36-beta packages and report issues if any.

Thanks
