### ISSUE TITLE
Inconsistent naming between DeviceContext.*SetConstantBuffer methods

### ISSUE THREAD

**Issue by mellinoe** [amerkoleci/Vortice.Windows#84]
There is some minor inconsistency in the naming of overloads on DeviceContext. For some stages, the single-buffer overload is named with a singular name (e.g. SetConstantBuffer). On others, it has a plural name, despite only taking one buffer (SetConstantBuffers).

* [VSSetConstantBuffer](https://github.com/amerkoleci/Vortice.Windows/blob/6a53f2d6760c64c1997d220b2c72c2e444eb9220/src/Vortice.Direct3D11/ID3D11DeviceContext.cs#L648)
* [DSSetConstantBuffers](https://github.com/amerkoleci/Vortice.Windows/blob/6a53f2d6760c64c1997d220b2c72c2e444eb9220/src/Vortice.Direct3D11/ID3D11DeviceContext.cs#L836)

**Comment by amerkoleci** [comment]
I just pushed new change that should fix this, I've removed the params usage in order to avoid the allocation, bumped back the 1.7.x beta version, we can gather other issues and I can release new stable 1.7.x version.
