### ISSUE TITLE
Can I use Vortice nuget packege with .Net Framework 4.7.2

### ISSUE THREAD

**Issue by AGIT-JVA** [amerkoleci/Vortice.Windows#88]
Actually My project is on .Net Framework 4.7.2. I have added Vortice.Direct2D1 packege. but when I run the project, I am getting an error,

Could not load file or assembly 'Vortice.Direct2D1, Version=1.8.0.0

**Comment by amerkoleci** [comment]
That doesn't make sense, net standard 2.0 is compatible with net4.6.1 or higher

**Comment by AGIT-JVA** [comment]
I have added  'Vortice.Direct2D1 version 1.8.16 so Why I am getting this error.

**Comment by amerkoleci** [comment]
Dude, give some more info?
I've just run the command: Install-Package Vortice.Direct2D1 -Version 1.8.16 and had no issues.

Closing now
