### ISSUE TITLE
Any plans for a (preview) NuGet package?

### ISSUE THREAD

**Issue by Sergio0694** [amerkoleci/Vortice.Windows#9]
Hi, first of all I wanted to say great job of picking up where SharpDX left off, this project is looking great so far! I'm working on a project that currently uses SharpDX ([ComputeSharp](https://github.com/Sergio0694/ComputeSharp)) and it looks like Vortice.Windows could replace both SharpDX and DotNetDxc for me (especially DotNetDxc, as it bundles old .dlls and it's not suitable for my use case anyway).

Are there any plans to publish Vortice.Windows on NuGet, at least as a preview package? That'd make it possible for 3rd party NuGet packages to reference it.

Additional question: I just noticed that the shader compiler code (with a partial port of the DotNetDxc code) in this repo is under a sample project - do you plan to integrate that code into Vortice.Windows (along with the necessary .dlls) or would we still need to reference the DotNetDxc package separately?

Thanks! 😄

**Comment by amerkoleci** [comment]
Hi,
Of course yes, you can currently use the myget feed and add it into nuget.config, I plan to release soon on nuget the official 1.0.0 version. 

I plan to have dxc compiler with all dlls supported as legacy d3d compiler. 

Thanks,

**Comment by nathan-alden** [comment]
@Sergio0694 Create a `nuget.config` file that lives next to your `.sln` file:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="myget-vortice" value="https://www.myget.org/F/vortice/api/v3/index.json" />
  </packageSources>
</configuration>
```
Then, make sure you check the "Include prerelease" check box:

![image](https://user-images.githubusercontent.com/1189759/63636938-57863600-c644-11e9-9e58-0bc7b4157787.png)

**Comment by Sergio0694** [comment]
Hey @amerkoleci - thank you for your reply!
That's good to hear, looking forward to the NuGet package!

What do you mean with "legacy d3d compiler"? I mean, why "legacy", I thought those .dlls were the official compiler for d3d shaders? (I might very well be wrong here).
I saw you commented on the [DirectX12GameEngine repo](https://github.com/Aminator/DirectX12GameEngine) by @Aminator (with whom I collaborated on my ComputeSharp repo), so I imagine you've had a peek at his code as well. You're saying that once the package is released then both of us will be able to just remove the [DotNetDxc](https://github.com/tgjones/DotNetDxc) reference (as well as the bundled .dlls) and just use Vortice.Windows for everything?
Just double checking to make sure I got this right 😄

@nathan-alden thank you for that snippet, I'll definitely try that out! The main issue for me at the moment though (which is preventing me from publishing my project to NuGet) is not SharpDX, but the DXCompiler. The DotNetDxc package has out of date .dlls that won't work in my scenario, and for local testing I'm just manually referencing the updated ones, but I can't for the love of me get them to be bundled correctly when creating a package. That's why I was hoping I could kill two birds with one stone with Vortice.Windows and just use this lib for everything 😅

**Comment by amerkoleci** [comment]
Hi,
Yes I plan to support both dxc and d3d compiler (legacy), that will be part of Vortice Shader Compiler.

Will post updates here, as I'm quite busy with my daily job, this is my side project tho :)

**Comment by amerkoleci** [comment]
I'm from Italy as well, ciao bello :)

**Comment by Sergio0694** [comment]
Thank you for the additional feedback, looking forward to the new updates then, and glad to hear I'll be able to replace both packages just with `Vertice.Windows` then, that's awesome 🚀

And yeah I figured this was just a side project for you, I'd say you're doing a great job so far though!
Buona serata! 😄

**Comment by amerkoleci** [comment]
Hi @Sergio0694,
Vortice.Dxc just landed (https://github.com/amerkoleci/Vortice.Windows/commit/cdd75d017ab5983300c0b5da2769db2a3bc0c830)

**Comment by Sergio0694** [comment]
Hey @amerkoleci - that was quick, awesome!
I'll try to move ComputeSharp from SharpDX to Vortice in the next few days then, thanks! 😄

**Comment by amerkoleci** [comment]
Nuget packages are on, closing now.
