### ISSUE TITLE
Direct Composition

### ISSUE THREAD

**Issue by MaximProzorov** [amerkoleci/Vortice.Windows#90]
Hi.

Are you planning to add Direct Composition?

**Comment by amerkoleci** [comment]
Isn't direct composition windows only?

**Comment by MaximProzorov** [comment]
> Isn't direct composition windows desktop only? Not UWP support?

Direct Composition can work on UWP, and, yes, it really windows desktop only.
But it was on SharpDx, and I consider this project as a SharpDX continuation.

**Comment by amerkoleci** [comment]
I see, will add it soon

**Comment by amerkoleci** [comment]
Here we go:
https://www.nuget.org/packages/Vortice.DirectComposition was just added the version is: 1.8.21

**Comment by MaximProzorov** [comment]
Thanks
