### ISSUE TITLE
Add support for WinUI 3 SwapChainPanel

### ISSUE THREAD

**Issue by mrjfalk** [amerkoleci/Vortice.Windows#91]
I've tried using this library with WinUI3 (Desktop) `SwapChainPanel`, but I get an exception when trying to cast my `SwapChainPanel` to a `ISwapChainPanelNative` interface, saying the interface is not supported.

I'm not a COM expert, so I might be wrong, but my guess is that this is due to the current ISwapChainPanelNative in Vortice.Windows is based on the interface in `windows.ui.xaml.media.dxinterop.h` while the WinUI 3 type should comes from  `microsoft.ui.xaml.media.dxinterop.h`.

Would it be possible to get support for WinUI3 SwapChainPanel as well?

**Comment by amerkoleci** [comment]
Absolutely yes, will add it tomorrow

**Comment by amerkoleci** [comment]
Can you please share the code you're trying to cast?

**Comment by mrjfalk** [comment]
I want to cast the `Microsoft.UI.Xaml.Controls.SwapChainPanel` into a `ISwapChainPanelNative` from `microsoft.ui.xaml.media.dxinterop.h`. You can find this interface inside this nuget: https://www.nuget.org/packages/Microsoft.WinUI (inside include/microsoft.ui.xaml.media.dxinterop.h):
```
[
    object,
    uuid( 63aad0b8-7c24-40ff-85a8-640d944cc325 ),
    local,
    pointer_default(unique)
]
interface ISwapChainPanelNative: IUnknown
{
    HRESULT SetSwapChain([in, annotation("_In_")] IDXGISwapChain *swapChain);
}
```

**Comment by amerkoleci** [comment]
So you're using ISwapChainPanelNative from Vortice.DXGI?

**Comment by mrjfalk** [comment]
Ye that's what I want to be able to do 👍

**Comment by amerkoleci** [comment]
Tomorrow will tell you how to do it, once I get on pc

**Comment by amerkoleci** [comment]
You need to to:
```
SwapChainPanel panel = ...;
ComObject comObject = new ComObject(panel);

Vortice.DXGI.ISwapChainPanelNative swapchainPanelNative = comObject.QueryInterfaceOrNull<Vortice.DXGI.ISwapChainPanelNative>();
swapchainPanelNative.SetSwapChain(_dxgiSwapChain);

```

Tell me if it works?

**Comment by mrjfalk** [comment]
That is essentially what I've done already, the `QueryInterfaceOrNull` just returns `null`. The problem is that the GUID of the Vortice.DXGI.ISwapChainPanelNative is incorrect when using it with WinUI3.

**Comment by amerkoleci** [comment]
Incorrect why? What is the correct GUID? If you provide more info I can gladly fix it.

**Comment by mrjfalk** [comment]
Because the Vortice.DXGI.ISwapChainPanelNative has the GUID of the **windows**.ui.xaml.media.dxinterop::ISwapChainPanelNative, which works with UWP **Windows**.UI.Xaml.Controls.SwapChainPanel while I'm using the WinUI3 **Microsoft**.UI.Xaml.Controls.SwapChainPanel interface has the same name but a new GUID and namespace: **microsoft**.ui.xaml.media.dxinterop::ISwapChainPanelNative

**Comment by amerkoleci** [comment]
Where can I find the microsoft.ui.xaml.media.dxinterop.h header file?

**Comment by mrjfalk** [comment]
In this nuget (inside the /include folder): https://www.nuget.org/api/v2/package/Microsoft.WinUI/3.0.0-preview2.200713.0

**Comment by amerkoleci** [comment]
Thanks, the 1.8.21 of Vortice.DXGI now has all the types you need under the Vortice.DXGI.WinUI namespace.

**Comment by mrjfalk** [comment]
Awesome, will try it out. Thanks!
