### ISSUE TITLE
BeginEvent method only shows the first 10 characters

### ISSUE THREAD

**Issue by jcant0n** [amerkoleci/Vortice.Windows#92]
Hi amerkoleci,

We are adding a new lowlevel API to WaveEngine for debugmakers, here is the implementation for DX12:

```
 /// <inheritdoc/>
public override void BeginDebugMarker(string label)
{
    this.CommandList.BeginEvent(label);
}

/// <inheritdoc/>
public override void EndDebugMarker()
{
    this.CommandList.EndEvent();
}

/// <inheritdoc/>
public override void InsertDebugMarker(string label)
{
    this.CommandList.SetMarker(label);
}
```

Testing it in a simple DrawTriangletest:
```
protected override void InternalDrawCallback(TimeSpan gameTime)
{
    var commandBuffer = this.commandQueue.CommandBuffer();

    commandBuffer.Begin();
    commandBuffer.BeginDebugMarker("01234567890123456789");
    RenderPassDescription renderPassDescription = new RenderPassDescription(this.frameBuffer, new ClearValue(ClearFlags.Target, Color.CornflowerBlue));
    commandBuffer.BeginRenderPass(ref renderPassDescription);

    commandBuffer.SetViewports(this.viewports);
    commandBuffer.SetScissorRectangles(this.scissors);
    commandBuffer.SetGraphicsPipelineState(this.pipelineState);
    commandBuffer.SetVertexBuffers(this.vertexBuffers);

    commandBuffer.Draw((uint)this.vertexData.Length / 2);

    commandBuffer.EndRenderPass();
    commandBuffer.EndDebugMarker();
    commandBuffer.End();

    commandBuffer.Commit();

    this.commandQueue.Submit();
    this.commandQueue.WaitIdle();
}
```
Debugging with Renderdoc:

![image](https://user-images.githubusercontent.com/1783366/96422628-8d975980-11f8-11eb-867f-31395820e6c6.png)

I have tried to adding this code to HelloDirect3D12, but the EndEvent method doesn't appear, just like someone had remove it.
But in the last nuget it is.

I have reviewed the binding code as well:
```
public void BeginEvent(string name)
{
    IntPtr handle = IntPtr.Zero;
    try
    {
        handle = Marshal.StringToHGlobalUni(name);
        BeginEvent(1, handle, name.Length);
    }
    finally
    {
        if (handle != IntPtr.Zero)
        {
            Marshal.FreeHGlobal(handle);
        }
    }
}
```

and nothing weird around here. 

Do you have any idea what it could be?

**Comment by amerkoleci** [comment]
Hi @jcant0n ,
How do you attach using renderdoc? I have trouble to run HelloDirect3D12 from RenderDoc?

**Comment by amerkoleci** [comment]
Anyway I found the issue, I was using the ANSI version of BeginEvent and SetMarker, now it should be fine.
Can you try with new 1.8.22 version?

**Comment by jcant0n** [comment]
Ok, I'm going to check it.

**Comment by jcant0n** [comment]
Same result, only 10 characters.

![image](https://user-images.githubusercontent.com/1783366/96436804-59c33080-1206-11eb-8dbf-beeb2f9f3c8a.png)

![image](https://user-images.githubusercontent.com/1783366/96436992-65165c00-1206-11eb-89e3-7555d0ff2a09.png)

**Comment by amerkoleci** [comment]
Can this be RenderDoc bug? Anyway how can I attach to RenderDoc?

**Comment by jcant0n** [comment]
I'm going to try with a native sample to check it.
About renderdoc, I just launch our test directly.

**Comment by amerkoleci** [comment]
I found the issue, the problem was the size was total size in bytes not string lenght, now it should be fine.
Please try and report back.

**Comment by jcant0n** [comment]
Awesome! this is working now.

![image](https://user-images.githubusercontent.com/1783366/96468151-0532ac00-122c-11eb-8e7f-4ccd90f48996.png)
