### ISSUE TITLE
IXAudio2.CreateSubmixVoice missing & XAudio2Fx API request

### ISSUE THREAD

**Issue by mmusu3** [amerkoleci/Vortice.Windows#93]
Hi, I would like to migrate from SharpDX to Vortice.Windows, however some APIs are missing including this one:
https://docs.microsoft.com/en-us/windows/win32/api/xaudio2/nf-xaudio2-ixaudio2-createsubmixvoice

I would also like to have access to the XAudio2Fx APIs seen here:
https://docs.microsoft.com/en-us/windows/win32/api/xaudio2fx/

Edit: One other thing I just found I need is to be able to create an AudioBuffer using my own data pointer. Currently the constructor for doing so is private. (Sorry about the extra request.)

These are some of the things still holding me back, it would be great to have them. Thanks for your work so far!

**Comment by amerkoleci** [comment]
CreateSubmixVoice + FX (Reverb + VolumeMetter)

**Comment by amerkoleci** [comment]
Added AudioBuffer ctor with IntPtr data as well.

**Comment by mmusu3** [comment]
Wow! That was quick thanks. That should cover all the missing APIs. However now that I have my code migrated I am having a startup crash issue in I think one of the XAudio threads that I'm trying to figure out.

**Comment by amerkoleci** [comment]
Ok, next is probably xapo bindings but not priority for me now.

**Comment by mmusu3** [comment]
I don't know what is causing this issue, sometime after CreateMasteringVoice has been called a System.ExecutionEngineException happens on an unnamed thread in an unknown module. Unfortunately I will have to continue with SharpDX for now.
Since the original topic of this issue has been addressed I will close it now. Thank you again for your swift response. I may open a new issue later when I get more time to investigate.

**Comment by amerkoleci** [comment]
Not sure why wasting time when you wanted to keep on SharpDX, anyway no problem.
Happy to help out.

**Comment by mmusu3** [comment]
No no! I don't want to stay with SharpDX but I have code that still works with it. I am trying to migrate to Vortice.Windows but am having an issue when switching over, as mentioned above. I will keep trying to get Vortice to work but cannot figure out what is happening at the moment.
I very much appreciate your effort here and don't want it to go to waste, but in the mean time I must keep using the SharpDX version of my code as it is currently working and does not have the issue. Please do not be discouraged by this, thank you.

**Comment by mmusu3** [comment]
I think I found the issue I am having. https://github.com/amerkoleci/Vortice.Windows/issues/94
