### ISSUE TITLE
Runtime crash due to IXAudio2EngineCallbackShadow.Vtbl getting garbage collected

### ISSUE THREAD

**Issue by mmusu3** [amerkoleci/Vortice.Windows#94]
The Vtbl property implementation for `IXAudio2EngineCallbackShadow` creates a new object every time the getter is called as seen here:
https://github.com/amerkoleci/Vortice.Windows/blob/ecb7c15a4b2ca3e1bc8ebb3722f886acb0c4fdb2/src/Vortice.XAudio2/IXAudio2EngineCallback.cs#L20

The created VTable object is never stored anywhere and so gets garbage collected. This causes the delegate pointers to become invalid and cause the runtime to crash when they are called from XAudio.
I believe that is what is happening in this issue comment: https://github.com/amerkoleci/Vortice.Windows/issues/47#issuecomment-580201116 and also in my previous issue: https://github.com/amerkoleci/Vortice.Windows/issues/93

It seems the line of code above had intended to be written as a readonly property initializer like so:
```cs
protected override CppObjectVtbl Vtbl { get; } => new VTable();
```
the same way that it is implemented in `ComObjectShadow` here:
https://github.com/amerkoleci/Vortice.Windows/blob/ecb7c15a4b2ca3e1bc8ebb3722f886acb0c4fdb2/src/Vortice.Runtime.COM/ComObjectShadow.cs#L47

However, the unmanaged memory allocated in the VTables in both these cases is never freed. `IncludeShadow` takes a different approach and just keeps one static instance around:
https://github.com/amerkoleci/Vortice.Windows/blob/ecb7c15a4b2ca3e1bc8ebb3722f886acb0c4fdb2/src/Vortice.DirectX/Direct3D/IncludeShadow.cs#L18
thus the unfreed memory may not be as much of an issue since the vtbl will last until the process ends anyway (unless maybe it can be used with collectible assemblies). I am unsure which is the better way to do it.

**Comment by amerkoleci** [comment]
Just pushed commit, tell me if it fixes the issue you're having?

**Comment by mmusu3** [comment]
Yes! It appears to all be working correctly now. Thank you again, now maybe I can drop SharpDX for good.

**Comment by mmusu3** [comment]
Oh no! I forgot one other thing I noticed, `EngineCallbackImpl` implements `ICallbackable.Shadow` but it is already implemented by its base class `CallbackBase`

**Comment by mmusu3** [comment]
Closing now. I will open new issues for any future problems.
