### ISSUE TITLE
Matrix4x4 and projection matrix creation

### ISSUE THREAD

**Issue by koosha72** [amerkoleci/Vortice.Windows#97]
**Is your feature request related to a problem? Please describe.**
I searched the entire source code and couldn't find an implementation of 4x4 matrix or methods like D3DXMatrixOrthoOffCenterLH.

**Describe the solution you'd like**
Implementing a complete 4x4 Matrix class and required methods to create ortho and perspective projection matrices.

**Comment by amerkoleci** [comment]
Mathematics is not part of this project, you can use methods from System.Numerics.
