### ISSUE TITLE
RSGetScissorRects does not offer a variant that returns count

### ISSUE THREAD

**Issue by shartte** [amerkoleci/Vortice.Windows#99]
**Describe the bug**
These are the variants of RSGetScissorRects that I can see:
```
void RSGetScissorRects(RawRect[] rects)
void RSGetScissorRects(int count, RawRect[] rects)
```

**Expected behavior**
I think in the second variant, `count` should be a `ref` parameter, since there's otherwise no way of actually getting the bound number of scissor rectangles.

It's theoretically possible to "detect" unbound scissor rectangles by comparing members of `rects` against `0`, but this seems unnecessary, since the original method will return the actual number in the `count` parameter.

See: https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-rsgetscissorrects

**Why do I need this:**
The DX11 example renderer for ImGui uses this method to "store" the previous rendering state so it can restore it after running through ImGui's rendering.

**Comment by amerkoleci** [comment]
Fixed now, closing.
